export const treatmentCategories = [
  { id: "3", name: "BRAIN AND SPINE SURGERY IN INDIA", category: "Brain and Spine Surgery" },
  { id: "11", name: "CANCER TREATMENT IN INDIA", category: "Cancer Treatment" },
  { id: "1", name: "CARDIAC SURGERY IN INDIA", category: "Cardiac Surgery" },
  { id: "12", name: "COSMETIC SURGERY IN INDIA", category: "Cosmetic Surgery" },
  { id: "13", name: "DENTAL TREATMENT IN INDIA", category: "Dental Treatment" },
  { id: "14", name: "EAR NOSE THROAT SURGERY IN INDIA", category: "Ear Nose Throat Surgery" },
  { id: "15", name: "EYE TREATMENT IN INDIA", category: "Eye Treatment" },
  { id: "16", name: "GASTROENTEROLOGY SURGERY IN INDIA", category: "Gastroenterology Surgery" },
  { id: "10", name: "GENERAL SURGERY IN INDIA", category: "General Surgery" },
  { id: "17", name: "GYNAECOLOGY TREATMENT IN INDIA", category: "Gynaecology Treatment" },
  { id: "18", name: "NEPHROLOGY TREATMENT IN INDIA", category: "Nephrology Treatment" },
  { id: "8", name: "NEUROLOGY TREATMENT IN INDIA", category: "Neurology Treatment" },
  { id: "19", name: "ORGAN TRANSPLANT SURGERY IN INDIA", category: "Organ Transplant Surgery" },
  { id: "2", name: "ORTHOPEDIC SURGERY IN INDIA", category: "Orthopedic Surgery" },
  { id: "20", name: "ROBOTIC SURGERY HOSPITAL IN INDIA", category: "Robotic Surgery" },
  { id: "21", name: "STEM CELL THERAPY IN INDIA", category: "Stem Cell Therapy" },
  { id: "4", name: "UROLOGY SURGERY IN INDIA", category: "Urology Surgery" },
  { id: "22", name: "WEIGHT LOSS TREATMENT IN INDIA", category: "Weight Loss Treatment" },
];
