export const treatmentCategories = [
  { id: "3", name: "BRAIN AND SPINE SURGERY IN INDIA", category: "Brain and Spine Surgery", icon: "Brain" },
  { id: "11", name: "CANCER TREATMENT IN INDIA", category: "Cancer Treatment", icon: "Activity" },
  { id: "1", name: "CARDIAC SURGERY IN INDIA", category: "Cardiac Surgery", icon: "Heart" },
  { id: "12", name: "COSMETIC SURGERY IN INDIA", category: "Cosmetic Surgery", icon: "Sparkles" },
  { id: "13", name: "DENTAL TREATMENT IN INDIA", category: "Dental Treatment", icon: "Smile" },
  { id: "14", name: "EAR NOSE THROAT SURGERY IN INDIA", category: "Ear Nose Throat Surgery", icon: "Ear" },
  { id: "15", name: "EYE TREATMENT IN INDIA", category: "Eye Treatment", icon: "Eye" },
  { id: "16", name: "GASTROENTEROLOGY SURGERY IN INDIA", category: "Gastroenterology Surgery", icon: "Pill" },
  { id: "10", name: "GENERAL SURGERY IN INDIA", category: "General Surgery", icon: "Scissors" },
  { id: "17", name: "GYNAECOLOGY TREATMENT IN INDIA", category: "Gynaecology Treatment", icon: "Baby" },
  { id: "18", name: "NEPHROLOGY TREATMENT IN INDIA", category: "Nephrology Treatment", icon: "Droplet" },
  { id: "8", name: "NEUROLOGY TREATMENT IN INDIA", category: "Neurology Treatment", icon: "Zap" },
  { id: "19", name: "ORGAN TRANSPLANT SURGERY IN INDIA", category: "Organ Transplant Surgery", icon: "HeartPulse" },
  { id: "2", name: "ORTHOPEDIC SURGERY IN INDIA", category: "Orthopedic Surgery", icon: "Bone" },
  { id: "20", name: "ROBOTIC SURGERY HOSPITAL IN INDIA", category: "Robotic Surgery", icon: "Bot" },
  { id: "21", name: "STEM CELL THERAPY IN INDIA", category: "Stem Cell Therapy", icon: "Dna" },
  { id: "4", name: "UROLOGY SURGERY IN INDIA", category: "Urology Surgery", icon: "Syringe" },
  { id: "22", name: "WEIGHT LOSS TREATMENT IN INDIA", category: "Weight Loss Treatment", icon: "Scale" },
];
