import { Hospital } from './types';

export const hospitalsData: Hospital[] = [
  {
    id: '1',
    name: 'Manal Medical Center',
    type: 'General Hospital',
    location: '123 Healthcare Blvd, Medical District',
    city: 'New York',
    state: 'NY',
    rating: 4.9,
    reviewCount: 1245,
    beds: 450,
    established: 1998,
    image: '/doctor.png',
    description: 'Manal Medical Center is a premier healthcare facility offering comprehensive medical services across multiple specialties. With state-of-the-art technology and a team of over 500 healthcare professionals, we provide exceptional patient care in a modern, comfortable environment.',
    shortDescription: 'Premier multi-specialty hospital with 450 beds and advanced medical technology',
    specialties: ['Cardiology', 'Orthopedics', 'Neurology', 'Oncology', 'Pediatrics', 'Emergency Medicine'],
    facilities: ['24/7 Emergency', 'ICU', 'Operating Rooms', 'Diagnostic Imaging', 'Laboratory', 'Pharmacy'],
    accreditations: ['Joint Commission', 'NABH', 'ISO 9001:2015'],
    emergency: true,
    parking: true,
    featured: true,
  },
  {
    id: '2',
    name: 'Heart & Vascular Institute',
    type: 'Specialty Hospital',
    location: '456 Cardiac Way, Downtown',
    city: 'Los Angeles',
    state: 'CA',
    rating: 4.8,
    reviewCount: 892,
    beds: 200,
    established: 2005,
    image: '/doctor-img 1.png',
    description: 'A world-renowned cardiac care facility specializing in heart and vascular diseases. Our institute features the latest in cardiovascular technology including hybrid operating rooms, advanced catheterization labs, and comprehensive cardiac rehabilitation programs.',
    shortDescription: 'Specialized cardiac and vascular care center with cutting-edge technology',
    specialties: ['Interventional Cardiology', 'Cardiac Surgery', 'Vascular Surgery', 'Heart Failure', 'Arrhythmia'],
    facilities: ['Cardiac Cath Lab', 'Cardiac ICU', 'Hybrid OR', 'Echo Lab', 'Stress Testing'],
    accreditations: ['ACC Accreditation', 'Chest Pain Center', 'Heart Failure Certification'],
    emergency: true,
    parking: true,
    featured: true,
  },
  {
    id: '3',
    name: 'University Medical Hospital',
    type: 'Teaching Hospital',
    location: '789 University Ave, Campus District',
    city: 'Chicago',
    state: 'IL',
    rating: 4.7,
    reviewCount: 2103,
    beds: 650,
    established: 1985,
    image: '/doctor-img2 1.png',
    description: 'A leading academic medical center affiliated with prestigious medical schools, providing cutting-edge treatments and participating in groundbreaking research. Our teaching hospital combines clinical excellence with medical education and innovation.',
    shortDescription: 'Academic teaching hospital with research programs and 650 beds',
    specialties: ['All Major Specialties', 'Research Programs', 'Clinical Trials', 'Advanced Procedures'],
    facilities: ['Research Labs', 'Medical Library', 'Simulation Center', 'Auditoriums', 'Student Housing'],
    accreditations: ['ACGME Accredited', 'Magnet Recognition', 'Research Excellence Award'],
    emergency: true,
    parking: true,
    featured: true,
  },
  {
    id: '4',
    name: 'City Trauma Center',
    type: 'Trauma Center',
    location: '321 Emergency Pkwy, Central',
    city: 'Houston',
    state: 'TX',
    rating: 4.9,
    reviewCount: 756,
    beds: 300,
    established: 2010,
    image: '/doctor.png',
    description: 'Level I Trauma Center providing 24/7 emergency care with immediate access to specialized trauma surgeons, neurosurgeons, and orthopedic specialists. Equipped with helicopter landing pad and advanced life support systems.',
    shortDescription: 'Level I Trauma Center with helicopter transport and 24/7 specialists',
    specialties: ['Trauma Surgery', 'Emergency Medicine', 'Critical Care', 'Burn Unit', 'Neurosurgery'],
    facilities: ['Helipad', 'Trauma Bays', 'Burn Unit', 'Hyperbaric Chamber', 'Blood Bank'],
    accreditations: ['ACS Level I Trauma', 'Burn Center Verified', 'STEMI Receiving'],
    emergency: true,
    parking: true,
    featured: true,
  },
  {
    id: '5',
    name: 'Orthopedic & Spine Hospital',
    type: 'Specialty Hospital',
    location: '654 Bone Lane, Medical Park',
    city: 'Phoenix',
    state: 'AZ',
    rating: 4.8,
    reviewCount: 634,
    beds: 150,
    established: 2008,
    image: '/doctor-img 1.png',
    description: 'Dedicated orthopedic and spine surgery center with specialized operating rooms and rehabilitation facilities. Our surgeons perform thousands of joint replacements and spine procedures annually with excellent outcomes.',
    shortDescription: 'Specialized orthopedic and spine surgery center',
    specialties: ['Joint Replacement', 'Spine Surgery', 'Sports Medicine', 'Hand Surgery', 'Foot & Ankle'],
    facilities: ['Specialized ORs', 'Physical Therapy', 'Sports Rehab', 'Pain Management', 'Imaging'],
    accreditations: ['Joint Replacement Certification', 'Blue Distinction Center'],
    emergency: false,
    parking: true,
    featured: false,
  },
  {
    id: '6',
    name: 'Wellness Rehabilitation Center',
    type: 'Rehabilitation Center',
    location: '987 Recovery Road, Suburbs',
    city: 'Philadelphia',
    state: 'PA',
    rating: 4.6,
    reviewCount: 428,
    beds: 100,
    established: 2012,
    image: '/doctor-img2 1.png',
    description: 'Comprehensive rehabilitation facility offering physical therapy, occupational therapy, and speech therapy services. Specializing in post-surgical recovery, stroke rehabilitation, and chronic pain management.',
    shortDescription: 'Full-service rehabilitation center for post-surgery and injury recovery',
    specialties: ['Physical Therapy', 'Occupational Therapy', 'Speech Therapy', 'Stroke Recovery', 'Pain Management'],
    facilities: ['Therapy Gyms', 'Aquatic Therapy', 'Wellness Center', 'Patient Rooms', 'Cafeteria'],
    accreditations: ['CARF Accredited', 'Stroke Rehabilitation Certified'],
    emergency: false,
    parking: true,
    featured: false,
  },
  {
    id: '7',
    name: "Children's Healthcare Hospital",
    type: 'Specialty Hospital',
    location: '159 Kids Way, Family District',
    city: 'Boston',
    state: 'MA',
    rating: 4.9,
    reviewCount: 1567,
    beds: 350,
    established: 1995,
    image: '/doctor.png',
    description: 'Pediatric hospital dedicated exclusively to children\'s healthcare, from newborns to adolescents. Features child-friendly environment, specialized pediatric equipment, and family-centered care approach.',
    shortDescription: 'Dedicated pediatric hospital with 350 beds and family-centered care',
    specialties: ['Pediatrics', 'Neonatology', 'Pediatric Surgery', 'Child Psychology', 'Pediatric Oncology'],
    facilities: ['NICU', 'PICU', 'Play Areas', 'Family Suites', 'Child Life Services'],
    accreditations: ["Children's Hospital Verified", 'Pediatric Trauma Center'],
    emergency: true,
    parking: true,
    featured: true,
  },
  {
    id: '8',
    name: 'Regional Medical Center',
    type: 'General Hospital',
    location: '753 Healthcare Drive, Westside',
    city: 'San Antonio',
    state: 'TX',
    rating: 4.5,
    reviewCount: 891,
    beds: 400,
    established: 2000,
    image: '/doctor-img 1.png',
    description: 'Full-service community hospital providing comprehensive healthcare services to the region. Known for patient satisfaction, quality outcomes, and convenient access to medical care.',
    shortDescription: 'Community-focused hospital with comprehensive medical services',
    specialties: ['Internal Medicine', 'Surgery', 'Obstetrics', 'Emergency Care', 'Radiology'],
    facilities: ['Emergency Room', 'Surgery Center', 'Maternity Ward', 'Radiology', 'Lab Services'],
    accreditations: ['Joint Commission', 'Patient Safety Excellence'],
    emergency: true,
    parking: true,
    featured: false,
  },
];

export const cities = Array.from(new Set(hospitalsData.map(h => h.city))).sort();
