import { Hospital } from './types';

export const hospitalsData: Hospital[] = [

  {
    id: '1',
    name: 'Apollo Fertility Center',
    type: 'Specialty Hospital',
    location: '2 & 3 Floor, above Visual Aids Centre, Plot 8, Ring Rd, Nirmal Puri, Nirmal Colony, Block 2, Lajpat Nagar, New Delhi-110024',
    city: 'New Delhi',
    state: 'Delhi',
    rating: 4.8,
    reviewCount: 520,
    beds: 50,
    established: 2015,
    image: '/doctor.png',
    description: 'Apollo Fertility Center, Lajpat Nagar was established in 2015 by Dr. Prathap C. Reddy, with a promise to fulfill the dreams of couples of having a successful pregnancy. Backed by 40 years of legacy of clinical excellence and outstanding expertise, the center specializes in exploring the reasons for infertility in men and women, and helps couples achieve pregnancy successfully. The team of fertility specialists follows a patient-centric approach with advanced technology and equipment. The clinic follows all clinical protocols that are tracked continuously to provide exceptional procedures for treating infertility in men and women, enhancing the chance of successful pregnancy.',
    shortDescription: 'Super-specialty fertility center with IVF and reproductive medicine backed by 40 years of Apollo legacy',
    specialties: ['Andrology', 'Urology', 'Fetal Medicine', 'Fertility', 'Reproductive Medicine', 'Endocrinology', 'Embryology', 'Laparoscopic Surgery'],
    facilities: ['Fertility Labs', 'IVF Center', 'Operating Theater', 'Laminar Air Flow', 'Laparoscopy Unit', 'Andrology Lab', 'Counseling Services', 'Physiotherapy', 'Diet & Nutrition'],
    accreditations: ['Apollo Healthcare Group', 'Clinical Excellence Certified', '40 Years Legacy'],
    expertise: ['In-Vitro Fertilization (IVF)', 'Laparoscopy', 'Male Diagnosis', 'Oocyte Vitrification', 'Screening and Tests', 'Embryo Transfer', 'Fertility Preservation'],
    infrastructure: ['8500 sq.ft facility area', 'Well-equipped fertility labs', '100 Class OT with laminar air flow', 'Advanced imaging equipment', 'State-of-the-art IVF lab', 'Modern consultation rooms'],
    emergency: false,
    parking: true,
    featured: true,
  },
  {
    id: '11',
    name: 'Indraprastha Apollo Hospital',
    type: 'General Hospital',
    location: 'Sarita Vihar, Mathura Road, New Delhi - 110076',
    city: 'New Delhi',
    state: 'Delhi',
    rating: 4.9,
    reviewCount: 1850,
    beds: 710,
    established: 1995,
    image: '/doctor.png',
    description: 'Indraprastha Apollo Hospital is a super-speciality hospital founded by the Apollo Hospitals Group in partnership with the Government of Delhi. Established in 1995, it became India\'s first hospital to be globally accredited by JCI in 2005. The hospital is one of the largest leaders in organ transplantation and cardiac sciences, with a world-renowned solid organ transplant program. Having performed over 500 paediatric liver transplants since 1998, the hospital has gained a 99.6% success rate in cardiac bypass (CABG) surgeries. With advanced technology including Da Vinci Robotic Surgery Systems and state-of-the-art imaging facilities, Indraprastha Apollo is one of the most desired healthcare destinations for patients from different nations.',
    shortDescription: 'India\'s first JCI-accredited super-speciality hospital with 710+ beds and world-class organ transplant program',
    specialties: ['Cardiac Sciences', 'Oncology', 'Neurosciences', 'Gastroenterology', 'Orthopedics', 'Urology', 'Organ Transplant', 'Pulmonology', 'Obstetrics and Gynaecology', 'Vascular Surgery', 'Paediatrics', 'Cosmetology', 'Ophthalmology'],
    facilities: ['Advanced Operation Theatres', 'Da Vinci Robotic Surgery', 'PET-CT and PET-MR Imaging', 'Minimally Invasive Surgery Units', 'Cardiac Bypass Surgery Center', 'Organ Transplant Center', 'Paediatric Liver Transplant Unit', '24/7 Emergency', 'ICU', 'Cardiac ICU'],
    accreditations: ['JCI (Joint Commission International) - 2005', 'NABH', 'Best Private Sector Hospital 2007', 'Best Indian Hospital for Medical Travel 2017', 'Best for Plastic Surgery 2020', 'Gold Award Smart Heart Care Hospital 2024', 'Golden Peacock Award Environment Management'],
    expertise: ['Organ Transplantation (500+ paediatric liver transplants)', 'Cardiac Sciences (99.6% CABG success rate)', 'Robotic Surgeries', 'Paediatric Liver Transplant', 'Minimally Invasive Surgeries', 'Advanced Cardiac Procedures', 'Complex Neurosurgery', 'Oncology Treatment'],
    infrastructure: ['15 acres campus', '600,000+ square feet facility', 'Advanced operation theatres with modern technology', 'Da Vinci Robotic Surgical Systems', 'PET-CT and PET-MR imaging technology', 'Minimally invasive surgery units for urology, gynaecology, oncology and cardiac surgery', 'State-of-the-art diagnostic facilities', 'Multiple ICUs and critical care units'],
    emergency: true,
    parking: true,
    featured: true,
  },
  {
    id: '2',
    name: 'Artemis Hospital',
    type: 'General Hospital',
    location: 'Sector 51, Near Unitech Cyber Park, Gurgaon - 122001',
    city: 'Gurgaon',
    state: 'Haryana',
    rating: 4.8,
    reviewCount: 1620,
    beds: 750,
    established: 2007,
    image: '/doctor.png',
    description: 'Artemis Hospital, established in 2007 in Gurgaon, is among the first JCI and NABH accredited hospitals in the region. This leading multi-specialty hospital with 750+ bed facilities is equipped with advanced technology and staffed by over 400+ highly skilled healthcare professionals with unbeatable expertise. The hospital has set a standard in the market by providing modern technology and the ultimate edition of equipment across 40+ specialties and 12+ centres of excellence. Having performed more than 30,000+ successful cardiac procedures, Artemis is popular globally for its patient-centric approach, offering facilities like air ambulance, airport transfers, and multi-language interpreters for international patients. The hospital is known for its best affordability, warm environment, and comprehensive services in advanced medical and surgical treatments.',
    shortDescription: 'Leading multi-specialty hospital with 750+ beds, 400+ doctors, and 30,000+ successful cardiac procedures',
    specialties: ['Oncology', 'Cardiology', 'Endocrinology', 'Ophthalmology', 'Hematology', 'Cardio Thoracic and Vascular Surgery', 'Organ Transplant', 'Obstetrics and Gynaecology', 'Gastroenterology', 'Neurology', 'Nephrology', 'Pulmonology', 'Robotic Surgery', 'Urology', 'Orthopedics', 'Bone Marrow Transplant'],
    facilities: ['Cardiac Cath Lab', 'Endovascular Operation Theatres', 'Cardiac Care Centers', '65+ ICU Beds (NICU, PICU, MICU)', '3 Tesla MRI', '64 Slice Cardiac CT', 'M6 CyberKnife Radiosurgery', 'Advanced Surgical Technology', 'Radiation Therapy', 'Air Ambulance', 'Airport Transfer Services', 'Multi-language Interpreters'],
    accreditations: ['JCI (Joint Commission International)', 'NABH', 'First JCI & NABH in Gurgaon', 'Best Bone Marrow Transplant Centre North India 2019', 'FICCI Healthcare Excellence Award 2018', 'Best Super Speciality Hospital Delhi NCR 2017', 'Patient Safety Award 2016', 'WHO Hand Hygiene Excellence Award 2011'],
    expertise: ['30,000+ successful cardiac procedures', 'Advanced cardiac procedures', 'Bone Marrow Transplantation', 'Robotic Surgery', 'CyberKnife Radiosurgery', 'Organ Transplantation', 'Cancer Care and Radiation Therapy', 'High-resolution diagnostics with 3 Tesla MRI', 'Complex cardiac surgeries'],
    infrastructure: ['525,000 sq.ft facility', '750+ hospital beds', '65+ ICU beds including NICU, PICU, and MICU', '3 Tesla MRI for high-resolution diagnostics', '64 Slice Cardiac CT for detailed heart imaging', 'M6 CyberKnife Radiosurgery system', 'State-of-the-art surgical technology', 'Advanced radiation therapy units', 'Cardiac Cath Lab and endovascular operation theatres', 'Comprehensive cancer care facilities'],
    emergency: true,
    parking: true,
    featured: true,
  },
  {
    id: '3',
    name: 'BLK-Max Super Speciality Hospital',
    type: 'General Hospital',
    location: 'Radha Soami Satsang, Pusa Rd, Rajendra Place, New Delhi - 110005',
    city: 'New Delhi',
    state: 'Delhi',
    rating: 4.9,
    reviewCount: 1450,
    beds: 650,
    established: 1959,
    image: '/doctor.png',
    description: 'BLK-Max Super Speciality Hospital was established by Dr. B. L. Kapur in 1959 and inaugurated by the respected Prime Minister, Pt. Jawahar Lal Nehru. This hospital is considered to be the largest and most honoured private hospital in Delhi NCR, accredited with JCI internationally and NABH & NABL nationally. BLK-Max Hospital is globally known for its clinical excellence, patient safety, and advanced technology in treatment. One of the biggest achievements is being North India\'s Largest Bone Marrow Transplant Centre, successfully achieving 100+ transplants yearly. The hospital was the first in Delhi to perform MUD (Matched Unrelated Donor) transplant and is among the first private hospitals to successfully perform Heart and Liver Transplant. With multi-lingual staff, professional interpreters, complimentary airport transportation, and comprehensive support services, BLK-Max provides outstanding clinical excellence to patients globally.',
    shortDescription: 'North India\'s largest bone marrow transplant centre with 650+ beds, established in 1959 by Dr. B. L. Kapur',
    specialties: ['Cardiac Care', 'Cancer Care', 'Neurosciences', 'Liver and Kidney Transplant', 'Bone and Joint', 'Robotic Surgery', 'IVF', 'Obstetrics', 'Gynaecology', 'Critical Care', 'Gastroenterology', 'Urology', 'ENT', 'Ophthalmology', 'Bone Marrow Transplant'],
    facilities: ['Heart Centre', 'Cancer Centre', 'Bone Marrow Transplant Centre', 'Institute for Digestive and Liver Diseases', 'Neurosciences Institute', 'Renal Sciences and Kidney Transplant Centre', 'Orthopedics and Spine Institute', 'Da Vinci Robotic Surgical Systems', '162+ Critical Care Beds', '125+ ICU Beds', '22+ Operation Beds', 'Air Filtration Systems', 'Gas Scavenging Systems', 'Non-Invasive Radiation Therapy', 'Airport Transfer Services', 'Multi-language Interpreters'],
    accreditations: ['JCI (Joint Commission International)', 'NABH', 'NABL', 'Best Multi Speciality Hospital by ET Healthworld', 'Quality Beyond Accreditation by AHPI 2017-2018', 'Best Multi Speciality Hospital by CNBC-TV18 2017', 'Trusted Hospital by India Today 2018'],
    expertise: ['North India\'s Largest Bone Marrow Transplant Centre (100+ transplants yearly)', 'First in Delhi to perform MUD (Matched Unrelated Donor) transplant', 'Heart Transplant', 'Liver Transplant', 'Kidney Transplant', 'Robotic Surgery (Urology, Gynaecology, Oncology)', 'Non-Invasive Radiation Therapy for tumor treatment', 'Advanced Cancer Care', 'Complex Cardiac Procedures', 'Minimally Invasive Surgical Procedures'],
    infrastructure: ['5 acres campus area', 'Largest private hospital in Delhi', '650+ hospital beds', '162+ critical care beds', '125+ Intensive Care Units', '22+ operation theatres', 'Advanced air filtration systems', 'Gas scavenging systems for sterile surgical environment', 'Da Vinci Robotic Surgical Systems', 'Non-Invasive Radiation Therapy units', 'Comprehensive cancer care facilities', 'State-of-the-art transplant units'],
    emergency: true,
    parking: true,
    featured: true,
  },
  {
    id: '4',
    name: 'Centre for Sight',
    type: 'Specialty Hospital',
    location: 'B-5/24, Safdarjung Enclave, New Delhi - 110029',
    city: 'New Delhi',
    state: 'Delhi',
    rating: 4.8,
    reviewCount: 980,
    beds: 100,
    established: 1996,
    image: '/doctor.png',
    description: 'Centre for Sight, Safdarjung Enclave eye hospital was established in 1996 by Dr. Mahipal S Sachdev, a prominent Padma Shri Award winner and one of India\'s most experienced ophthalmologists. The hospital is accredited with NABH certification and is among the leading eye hospitals in India, with 47+ centres across the country treating patients with exceptional care. The Centre for Sight is a complete eye care hospital that has been serving vision care in India since 1996, ranking among the top eye care hospitals in the country. The hospital maintains international standards with the latest and most advanced diagnostic machines and surgical equipment, including Robotic Assisted surgical equipment. With a team of well-experienced and skilled doctors, the hospital performs both surgical and non-surgical eye treatments, providing global standards of eye care with a patient-centric approach while maintaining ethical norms and practices.',
    shortDescription: 'Leading eye care hospital with 47+ centres across India, founded by Padma Shri awardee Dr. Mahipal S Sachdev',
    specialties: ['Cataract Surgery', 'Glaucoma Surgery', 'LASIK Surgery', 'Refractive Surgery', 'Cornea Transplant', 'Oculoplasty', 'Retina Services', 'Elita SILK Surgery', 'SMILE Eye Surgery', 'ICL (Implantable Collamer Lens) Surgery', 'Computer Vision Syndrome', 'Retina and Uvea', 'Retinoblastoma', 'Keratoconus Treatment', 'Contoura Vision Surgery', 'MICS (Micro Incision Cataract Surgery)', 'Phaco (Phacoemulsification)'],
    facilities: ['Cataract Surgery Centre', 'LASIK and Refractive Surgery Centre', 'Retina Services Centre', 'Glaucoma Management Centre', 'Paediatric Ophthalmology', 'Oculoplasty Centre', 'Robotic Assisted Surgical Equipment', 'Advanced Diagnostic Machines', 'State-of-the-art Surgical Equipment', 'Vision Testing Labs', 'Pre and Post-operative Care Units'],
    accreditations: ['NABH Accreditation for Quality and Patient Safety 2019', 'Frost and Sullivan Award Eye Care Provider 2010', 'FICCI Healthcare Excellence Award Operational Excellence 2012', 'Frost and Sullivan Award Eye Care Provider 2014', 'Padma Shri Award to Founder Dr. Mahipal S. Sachdev 2015', 'Frost and Sullivan Best Eye Hospital India 2017', 'ET Healthworld Awards Excellence in Ophthalmology 2020', 'Global Healthcare Excellence Award Best LASIK Eye Surgery Provider 2022'],
    expertise: ['Comprehensive eye care since 1996', 'Advanced LASIK and refractive surgeries', 'Robotic-assisted eye surgeries', 'Micro-incision cataract surgery (MICS)', 'SMILE (Small Incision Lenticule Extraction) Eye Surgery', 'ICL implantation procedures', 'Cornea transplantation', 'Retina and uvea treatments', 'Glaucoma surgical and medical management', 'Paediatric ophthalmology treatments', 'Contoura Vision Surgery', 'Keratoconus treatment'],
    infrastructure: ['47+ centres across India', 'International standard facilities', 'Latest and most advanced diagnostic machines', 'State-of-the-art surgical equipment', 'Robotic Assisted surgical systems', 'Advanced imaging and testing technology', 'Modern operation theatres', 'Patient-centric care infrastructure', 'Comprehensive pre and post-operative care facilities', 'Vision correction technology labs'],
    emergency: false,
    parking: true,
    featured: true,
  },
  {
    id: '7',
    name: 'Cosmodent Dental Clinic',
    type: 'Specialty Hospital',
    location: '548-SP, Sector 39, Near Medanta Hospital, Gurugram',
    city: 'Gurgaon',
    state: 'Haryana',
    rating: 5.0,
    reviewCount: 850,
    beds: 20,
    established: 2013,
    image: '/doctor.png',
    description: 'Cosmodent Dental Clinic in Gurgaon was established in 2013 with a clear purpose of providing comprehensive dental care to all patients. The clinic is equipped with advanced medical technology and provides patient-centric dental treatments, completely dedicated to offering oral health solutions to individuals and families from India and different countries. The main aim is to provide painless treatments, advanced technology, and affordability under one roof. With a team of well-trained staff and expert dentists experienced in cosmetic, implant, orthodontic, and restorative treatments, the clinic promises long-lasting results with comfort. Best acknowledged for excellence in smile design, dental implants, and aesthetic dentistry, Cosmodent is very popular among international patients who have received top-quality treatment. The clinic has successfully treated over 1000+ patients and achieved a 5-star rating for patient experience and quality treatment.',
    shortDescription: 'Leading dental clinic specializing in implants, cosmetic dentistry, and smile design with 5-star patient ratings',
    specialties: ['Dental Implants', 'Cosmetic Dentistry', 'Orthodontics', 'Restorative Treatments', 'Smile Design', 'Aesthetic Dentistry', 'Implantology', 'Endodontics', 'Prosthodontics', 'Implant Surgeries', 'Smile Makeover', 'Teeth Whitening', 'Veneers', 'Dental Crowns', 'Root Canal Treatment'],
    facilities: ['Digital X-rays and Imaging Systems', 'Implant Surgery Department', 'Cosmetic Treatment Department', 'Orthodontics Department', 'Clean and Safe Patient Lounges', 'Wheelchair and Stretcher Services', 'International Patient Coordination', 'Accommodation Support Services', 'Advanced Dental Equipment', 'Sterilization and Hygiene Systems', 'Consultation Rooms'],
    accreditations: ['One of the Best Dental Clinics in Gurgaon', '5-Star Rating for Patient Experience', '1000+ Successful Treatments', 'International Standards of Hygiene', 'Member of International Dental Conferences'],
    expertise: ['1000+ patients treated from India and internationally', 'High success rate in critical implant surgeries', 'Advanced smile design and makeovers', 'Painless dental treatments', 'Complex implant procedures', 'Full mouth rehabilitation', 'Cosmetic smile transformations', 'International standard implantology', 'Aesthetic dentistry excellence', 'Orthodontic corrections'],
    infrastructure: ['Advanced digital X-ray systems', 'State-of-the-art imaging technology', 'Separate departments for implants, cosmetics, and orthodontics', 'Clean and safe patient lounges', 'International standard hygiene facilities', 'Modern dental chairs and equipment', 'Advanced sterilization systems', 'Wheelchair and stretcher support available', 'International patient coordination center', 'Comfortable waiting areas'],
    emergency: false,
    parking: true,
    featured: true,
  },
  {
    id: '8',
    name: 'Fortis Escorts Heart Institute',
    type: 'General Hospital',
    location: 'Sukhdev Vihar Metro Station, Okhla Road, New Delhi - 110025',
    city: 'New Delhi',
    state: 'Delhi',
    rating: 4.9,
    reviewCount: 2150,
    beds: 310,
    established: 1988,
    image: '/doctor.png',
    description: 'Fortis Escorts Heart Institute (FEHI) was established in 1988 as the flagship hospital of the Fortis Healthcare group. The hospital is popularly known for its outstanding cardiac care services in India, serving for over 3 decades and is considered the largest private cardiac hospital in the Asia Pacific region. Accredited with NABH, NABL, and JCI globally, the hospital has performed breathtaking records including 80,000+ CABG surgeries, 53,000+ PTCAs (Angioplasties), 18,000+ Congenital Heart Procedures, and 173,000+ Angiographies. Equipped with 310+ beds including 158 ICU beds and 9 advanced operation theatres, the hospital is served by a team of 200 experienced cardiologists and cardiac surgeons (including Padma Bhushan and Padma Shri awardees) teaming up with 1600 trained staff. A pioneer in India, being the first to perform TAVI, BVS, Directional Atherectomy, and Bioprosthetic Valve Replacement, the hospital also achieved a Guinness World Record for conducting the most cholesterol tests in an eight-hour timeframe.',
    shortDescription: 'Asia Pacific\'s largest private cardiac hospital with 310+ beds and 80,000+ CABG surgeries since 1988',
    specialties: ['Cardiac Sciences', 'Infertility Medicine', 'Dental Science', 'Endocrine Surgery', 'Liver Transplant and Hepatobiliary Sciences', 'Neurology', 'Ophthalmology', 'Pulmonology', 'Organ Transplant', 'Thoracic Surgery', 'Bone and Joint Replacement', 'Kidney and Urology'],
    facilities: ['Heart Institute', 'Institute of Liver and Digestive Diseases', 'Institute of Kidney and Urology', 'Bone and Joint Replacement Centre', 'Advanced Cath Labs', '158 ICU Beds', '9 Advanced Operation Theatres', 'Robotic Surgery', 'Shockwave Lithotripsy for Calcified Arteries', 'Specialized Cardiac Care', 'TAVI (Transcatheter Aortic Valve Implantation)', 'Cardiac Rehabilitation'],
    accreditations: ['JCI (Joint Commission International)', 'NABH', 'NABL', 'Best Hospital in Cardiology by Times Healthcare Achievers', 'Best Hospital in Cardiology by CNBC TV18', 'Best Hospital in Cardiology by ICICI Lombard', 'Best Hospital in Cardiology by The Week', 'Best Hospital in Cardiology by ET Health Care Awards', 'Gold Award for Best Healthcare Delivery Brand', 'India Healthcare Award 2012 for Finest Single Speciality Hospital (Cardiology)', 'Guinness World Record for Cholesterol Tests'],
    expertise: ['80,000+ CABG surgeries performed', '53,000+ PTCAs (Angioplasties)', '18,000+ Congenital Heart Procedures', '173,000+ Angiographies', 'First in India to perform TAVI', 'First in India to perform BVS (Bioresorbable Vascular Scaffold)', 'First in India to perform Directional Atherectomy', 'First in India to perform Bioprosthetic Valve Replacement', 'Advanced robotic surgeries', 'Shockwave Lithotripsy for calcified arteries', 'Complex cardiac procedures', 'Liver and kidney transplants', 'Congenital heart disease treatment'],
    infrastructure: ['15 acres campus', '310+ hospital beds', '158 ICU beds', '9 advanced operation theatres', 'State-of-the-art infrastructure', 'Advanced Cath Labs for complex cardiac procedures', 'Latest cardiac care technology', 'Modern robotic surgery systems', 'Patient-friendly environment', 'High-tech medical machines', 'Specialized cardiac care units', 'Comprehensive diagnostic facilities'],
    emergency: true,
    parking: true,
    featured: true,
  },
  {
    id: '9',
    name: 'Fortis Memorial Research Institute',
    type: 'General Hospital',
    location: 'Opposite HUDA City Centre, Sector - 44, Gurgaon - 122002',
    city: 'Gurgaon',
    state: 'Haryana',
    rating: 4.9,
    reviewCount: 2280,
    beds: 310,
    established: 2001,
    image: '/doctor.png',
    description: 'Fortis Memorial Research Institute (FMRI) was established in 2001 with a commitment to provide great healthcare with clinical excellence and a patient-centric approach for the better well-being of society. As the main hospital of Fortis Healthcare and a leading organization in India for integrated healthcare services, FMRI is a state-of-the-art multi-specialty, quaternary care hospital with advanced technology. Accredited with NABH, NABL, CEA, and JCI, the hospital is known as the "Mecca of Healthcare" for the Asia Pacific region and has set standards for institutions globally. Ranked 34th Globally and 14th nationally by Newsweek for Best Hospitals, FMRI is committed to delivering positive results with care and compassion, respecting all religions, backgrounds, and opinions. The hospital provides complete assistance with accommodation and food arrangements for patients and their families, equipped with cutting-edge technology including 3.0 Tesla MRI, 256-Slice CT scanner, and Da Vinci Robotic Surgical Systems.',
    shortDescription: 'Asia Pacific\'s "Mecca of Healthcare" with 310+ beds, ranked 34th globally by Newsweek, featuring quaternary care',
    specialties: ['Cardiac Sciences', 'Infertility Treatment', 'Dental Science', 'Endocrine Surgery', 'Neurology', 'Ophthalmology', 'Nephrology', 'Oncology', 'Urology', 'Organ Transplant', 'Neuro Surgery', 'Haematology', 'Paediatric', 'Plastic and Reconstructive Surgery', 'Vascular Surgery', 'General Surgery', 'Thoracic Surgery'],
    facilities: ['15 Advanced Operation Suites', 'Da Vinci Robotic Surgical Systems', '3.0 Tesla MRI', '256-Slice CT Scanner', 'Advanced Sterilization Systems', 'Minimally Invasive Surgery Units', 'Central Sterile Supply Department (CSSD)', 'Cardiac Care Units', 'Oncology Treatment Centers', 'Bone Marrow Transplant Unit', 'ICU and Critical Care', 'Accommodation Support Services'],
    accreditations: ['JCI (Joint Commission International)', 'NABH', 'NABL', 'CEA', 'Ranked 34th Globally by Newsweek World\'s Best Smart Hospital 2024', 'Ranked 14th Nationally by Newsweek Best Hospitals India 2024', 'Economic Times Health Awards Excellence in Neurosurgery 2024', 'Economic Times Health Awards Multimodality Cancer Treatment 2024', 'Economic Times Health Awards Excellence in Surgery 2024', 'Economic Times Health Awards Bone Marrow Transplantation 2024', 'Rank No. 2 by The Week Magazine Delhi NCR Best Private Hospital 2019-2021', 'FICCI Medical Value Travel Awards Excellence in Medical Oncology 2025', 'DL SHAH Awards Certificate of Merit Quality Improvement 2015', 'APSIC Centre of Excellence for CSSD'],
    expertise: ['Quaternary care hospital', 'Advanced neurosurgery', 'Multimodality cancer treatment', 'Bone marrow transplantation', 'Medical oncology excellence', 'Minimally invasive robotic surgeries', 'Complex cardiac procedures', 'Organ transplantation', 'High-definition diagnostic imaging with 256-Slice CT', 'Advanced MRI diagnostics with 3.0 Tesla', 'Plastic and reconstructive surgery', 'Comprehensive vascular surgery'],
    infrastructure: ['11 acres campus', '310+ hospital beds (expandable to 1000 beds)', '15 operation suites with advanced sterilization', '3.0 Tesla MRI for high-definition imaging', '256-Slice CT scanner for accurate diagnostics', 'Da Vinci Robotic Surgical Systems', 'Minimally invasive surgery units for urology, gynaecology, and general surgery', 'State-of-the-art quaternary care infrastructure', 'Centre of Excellence Central Sterile Supply Department', 'Patient and family accommodation facilities', 'Multi-specialty integrated healthcare infrastructure', 'Advanced diagnostic and treatment technology'],
    emergency: true,
    parking: true,
    featured: true,
  },
  {
    id: '13',
    name: 'Manipal Hospital Dwarka',
    type: 'General Hospital',
    location: 'Dwarka Sector 6, New Delhi - 110075',
    city: 'New Delhi',
    state: 'Delhi',
    rating: 4.8,
    reviewCount: 1890,
    beds: 380,
    established: 1953,
    image: '/doctor.png',
    description: 'Manipal Hospital Dwarka belongs to the Manipal Education and Medical Group, which was founded in 1953 as Kasturba Medical College in Manipal, Karnataka. As India\'s third largest established healthcare group, the hospital is a multi-specialty facility offering a wide range of medical services and world-class healthcare at the most affordable cost. Accredited by NABH and NABL, the hospital is guided by the 4 A principles: Accessibility, Affordability, Awareness, and Accountability. With a team of 43 experienced doctors (some internationally acclaimed), trained staff, and nurses, the hospital has achieved various awards and honours for their selfless services. The hospital is dedicated to creating an environment of healing, innovation, and trust, serving as a pillar of healthcare in the communities it serves. With 24-hour emergency and trauma services with faster response, the hospital offers comprehensive medical facilities under one roof.',
    shortDescription: 'Part of India\'s 3rd largest healthcare group with 380+ beds, guided by 4 A principles of accessibility and affordability',
    specialties: ['Anesthesiology', 'Bariatric Surgery', 'Cardiology', 'Critical Care', 'Dermatology', 'Diabetology and Endocrinology', 'ENT', 'Gastroenterology', 'Haematology', 'Internal Medicine', 'Nephrology', 'Nuclear Medicine', 'Gynecology and Obstetrics', 'Orthopedics', 'Plastic and Reconstructive Surgery', 'Radiology', 'Rheumatology', 'Spine Surgery', 'Urology'],
    facilities: ['Cancer Care Centre', 'Cardiology Department', 'Cardiothoracic Vascular Surgery', 'Emergency Medicine', 'Gastrointestinal Science', 'Laparoscopic Surgery', 'Liver Transplantation & Hepato-Pancreato Biliary Surgery', 'Nephrology', 'Neurology', 'Neurosurgery', 'Organ Transplant', 'Paediatric And Child Care', 'Renal Sciences', '13 Advanced Operation Theatres', '118 Critical Care Beds', '24-Hour Emergency Services'],
    accreditations: ['NABH', 'NABL', 'Best Multi Speciality Hospital in Delhi NCR 2021', 'Best Hospital for Patient Safety by FICCI 2020', 'Best Hospital for Emergency and Critical Care 2019', 'Best Hospital for Gastroenterology by Times of India 2018', 'Best Hospital for Orthopaedics by Indian Healthcare Awards 2017'],
    expertise: ['Team of 43 experienced doctors including internationally acclaimed specialists', 'Advanced emergency and trauma care with 24-hour services', 'Comprehensive gastroenterology services', 'Orthopedic excellence', 'Critical care with 118 advanced beds', 'Patient safety protocols', 'Liver transplantation and HPB surgery', 'Laparoscopic surgical procedures', 'Cardiothoracic vascular surgery', 'Organ transplantation', 'Pediatric and child care', 'Rheumatology treatments'],
    infrastructure: ['560,000 sq.ft facility', '380 hospital beds', '13 high-quality advanced operation theatres', '118 critical care beds with advanced technology', 'State-of-the-art medical equipment', '24-hour emergency and trauma services', 'Modern diagnostic facilities', 'Comprehensive medical services under one roof', 'Patient-friendly environment', 'Advanced technology infrastructure', 'Dedicated transplant units', 'Specialized surgical suites'],
    emergency: true,
    parking: true,
    featured: true,
  },
  {
    id: '14',
    name: 'Marengo Asia Hospital',
    type: 'General Hospital',
    location: 'Sector 16, Plot no. 1, Faridabad - 121002',
    city: 'Faridabad',
    state: 'Haryana',
    rating: 4.8,
    reviewCount: 1420,
    beds: 450,
    established: 2007,
    image: '/doctor.png',
    description: 'Marengo Asia Hospital, Faridabad (formerly QRG Health City) was established in 2007 by the QRG Group and has achieved the title of "Best Emerging Critical Care Hospital in Delhi NCR". Accredited with NABH and NABL certificates, the hospital is recognized as a multi-specialty hospital serving high-quality treatment at affordable costs. Under the leadership of Dr. Raajiv Singhal, Founding Member, Managing Director and Group CEO, the hospital has set new standards for healthcare institutes through quality, innovation, and positive outcomes. The hospital is guided by the 4 A principles: Accessibility, Affordability, Awareness, and Accountability. With a patient-centric approach and centres of excellence, Marengo Asia Hospital offers preventive health check-up programs including Well Women, Senior Citizens, and Executive Health Checks. The hospital has trained staff, an experienced team of doctors, and dedicated support teams for post-operative medical needs. With a separate help desk for international patients, advanced technology, and high-quality equipment, the hospital monitors and treats patients from all backgrounds with exceptional care.',
    shortDescription: 'Multi-specialty hospital with 450+ beds, titled "Best Emerging Critical Care Hospital in Delhi NCR"',
    specialties: ['Cardiology', 'Urology', 'Neurology', 'Dermatology', 'Gastroenterology', 'Orthopedics', 'Paediatric', 'Nephrology', 'Dentistry', 'Liver Transplant and Biliary Sciences', 'Renal Sciences', 'Bone Marrow Transplant', 'Oncology', 'Critical Care', 'Bariatric Surgery', 'Respiratory and Sleep Medicine', 'Diabetes and Metabolic Disorders', 'Fertility and IVF'],
    facilities: ['Cancer Care Center', 'Cardiac Sciences', 'Cardiac Cath Labs', 'Modular Operation Theatres', 'EPS Labs', 'Endoscopic Ultrasound', '3T MRI', '128 Slice CT Scanner', 'Dialysis Unit', 'Neonatal ICU', 'General and Minimally Invasive Surgery', 'Suite Rooms', 'Deluxe Rooms', 'Twin Sharing Rooms', 'General Wards', '24-Hour Emergency Services'],
    accreditations: ['NABH', 'NABL', 'Best Emerging Critical Care Hospital in Delhi NCR'],
    expertise: ['Cancer Care and Oncology', 'Cardiac Sciences excellence', 'Critical Care services', 'Neurosciences', 'Orthopedic treatments', 'Nephrology and Renal Sciences', 'Gastroenterology', 'Minimally Invasive Surgery', 'Bariatric Surgery', 'Bone Marrow Transplant', 'Liver Transplant and Biliary Sciences', 'Fertility and IVF treatments', 'Respiratory and Sleep Medicine', 'Diabetes and Metabolic Disorders management'],
    infrastructure: ['40,000+ sq.ft facility', '450+ hospital beds', 'Emergency beds', 'ICU beds', 'Critical Care units', 'Dialysis unit', 'Neonatal ICU', 'Cardiac Cath Labs', 'Modular operation theatres', 'EPS labs', '3T MRI imaging', '128 Slice CT scanner', 'Endoscopic Ultrasound', 'Suite rooms, deluxe rooms, twin sharing and general wards'],
    emergency: true,
    parking: true,
    featured: true,
  },
  {
    id: '15',
    name: 'Max Super Speciality Hospital',
    type: 'General Hospital',
    location: 'Mandir Marg, Press Enclave, Saket Institution Area, Saket, New Delhi - 110017',
    city: 'New Delhi',
    state: 'Delhi',
    rating: 4.9,
    reviewCount: 2450,
    beds: 539,
    established: 2005,
    image: '/doctor.png',
    description: 'Max Super Speciality Hospital, Saket was established in 2005 and is considered one of the top healthcare services in India. Accredited with NABH, ISO, and JCI certificates, the hospital is renowned for its outstanding services and expertise in various specialties. One of the biggest achievements is being the first in India to be accredited by the Surgical Review Corporation, USA as a Centre of Excellence in Metabolic and Bariatric Surgery. The hospital features Asia\'s First and World\'s Third Brain Suite, the first neurosurgical operation theatre in Asia that performs Intraoperative MRIs during surgery. Expanded across 3 acres with two blocks - East Block (unit of Devki Devi Foundation) and West Block (unit of Max Healthcare Institute Limited), the hospital provides air ambulance services for medical evacuation and accommodation assistance for seamless patient experience. With advanced technology including Da Vinci Xi Robotic System, Stereotactic Body Radiation Therapy (SBRT), and Bi-Plane Digital Cath Lab, Max Super Speciality Hospital ensures all facilities are available under one roof with a patient-centric approach.',
    shortDescription: 'Multi-specialty hospital with 539+ beds, Asia\'s First Brain Suite, and first in India for Bariatric Surgery Centre of Excellence',
    specialties: ['Oncology', 'Cardiology and Cardiac Surgery', 'Neurology and Neurosurgery', 'Orthopedics', 'Gastroenterology', 'Hematology', 'Urology and Kidney Transplant', 'ENT Surgery', 'Organ Transplant', 'Nephrology', 'Dental Care', 'Joint Replacement', 'Lung Transplant', 'Minimal Access and Laparoscopic Surgery', 'Robotic Surgery', 'Liver and Biliary Sciences'],
    facilities: ['Cancer Care Center', 'Heart and Vascular Sciences', '50 Critical Care Beds', 'Specialized Endoscopy Unit', 'Dialysis Center', 'Transplant Medicine', 'Brain Suite with Intraoperative MRI', 'Da Vinci Xi Robotic System', 'Stereotactic Body Radiation Therapy (SBRT)', 'Bi-Plane Digital Cath Lab', 'Air Ambulance Services', 'Minimal Access Surgery Units', 'Musculoskeletal Sciences Center', 'Accommodation Assistance'],
    accreditations: ['JCI (Joint Commission International)', 'NABH', 'ISO', 'Surgical Review Corporation USA - Centre of Excellence in Metabolic and Bariatric Surgery', 'FICCI Healthcare Excellence Award for Operational Excellence', 'Quality Beyond Accreditation Award by AHPI 2020', 'Award for Pulmonary and Critical Care by India\'s Most Trusted Healthcare Awards 2019', 'Award for Excellence in Healthcare by Express Healthcare 2008', 'D L Shah National Award for Economics of Quality by Quality Council of India 2009'],
    expertise: ['Asia\'s First and World\'s Third Brain Suite', 'First in India - Centre of Excellence in Metabolic and Bariatric Surgery', 'Intraoperative MRI during neurosurgery', 'Da Vinci Xi Robotic Surgery with minimally invasive procedures', 'Stereotactic Body Radiation Therapy (SBRT) for tumors', 'Advanced cardiovascular procedures with Bi-Plane Digital Cath Lab', 'Organ transplantation (kidney, lung, liver)', 'Complex neurosurgical procedures', 'Cancer care with radiation therapy', 'Joint replacement and orthopedic surgeries', 'Minimal access and laparoscopic surgery', 'Pulmonary and critical care'],
    infrastructure: ['3 acres campus across East Block and West Block', '539+ hospital beds', '50 Critical Care Beds', 'Brain Suite with Intraoperative MRI capability', 'Da Vinci Xi Robotic Surgical System', 'Bi-Plane Digital Cath Lab for cardiovascular and neurovascular surgeries', 'Stereotactic Body Radiation Therapy (SBRT) system', 'Specialized Endoscopy Unit', 'High-quality dialysis center', 'Advanced operation theatres', 'Air ambulance facility', 'Comprehensive diagnostic imaging'],
    emergency: true,
    parking: true,
    featured: true,
  },
  {
    id: '16',
    name: 'Medanta - The Medicity Hospital',
    type: 'General Hospital',
    location: 'Medanta - The Medicity, Gurgaon - 122001',
    city: 'Gurgaon',
    state: 'Haryana',
    rating: 4.9,
    reviewCount: 3250,
    beds: 1600,
    established: 2009,
    image: '/doctor.png',
    description: 'Medanta - The Medicity Hospital, Gurugram was founded in 2009 by Dr. Naresh Trehan, a well-reputed and renowned cardiovascular and cardiothoracic surgeon. The hospital is committed to providing affordable and advanced medical treatments to patients from all backgrounds. Accredited with JCI, NABL, and NABH certificates, Medanta Gurugram is ranked as the Top and Best Private Hospital in India (2020, 2021, 2022, 2023, 2024, and 2025). Featured among the top 250 global hospitals in the Newsweek World\'s Best Hospitals Survey 2023, the hospital demonstrates excellent care and commitment to countless patients. With over 900 skilled specialists and a team of trained healthcare professionals, the hospital is equipped with advanced technology including 256-Slice CT Scanner, 3.0 Tesla MRI, PET-CT, and CyberKnife Robotic Radiosurgery. The hospital has achieved remarkable milestones including 15,000+ cardiac surgeries, 2,500+ joint replacements, 500+ Living Donor Liver Transplants (highest in India, 2nd in the world), and Asia\'s First Bloodless Bone Marrow Transplant. Medanta was also India\'s first to launch Air Ambulance services in 2013.',
    shortDescription: 'India\'s Best Private Hospital with 1600+ beds, founded by Dr. Naresh Trehan, ranked top 250 globally by Newsweek',
    specialties: ['Cardiac Sciences', 'Oncology', 'Neurosciences', 'Liver and Digestive Sciences', 'Bone and Joint Institute', 'Kidney and Urology Institute', 'Plastic, Aesthetic and Reconstructive Surgery', 'Gastroenterology', 'Cardiology', 'Gynaecology', 'Robotic Surgery'],
    facilities: ['Heart Institute', 'Institute of Neurosciences', 'Cancer Institute', 'Bone and Joint Institute', 'Institute of Gastroenterology Sciences', '1390+ Operation Suites', '270+ ICU Beds', '40+ Modular Operation Theatres with Laminar Air Flow', 'Hybrid Cath Labs', '256-Slice CT Scanner', '3.0 Tesla MRI', 'PET-CT', 'CyberKnife Robotic Radiosurgery', 'Air Ambulance Services', 'Real-time MRI Scans'],
    accreditations: ['JCI (Joint Commission International)', 'NABL', 'NABH', 'Newsweek World\'s Best Hospitals Top 250 Global 2023', 'Best Private Hospital in India 2020-2025', 'Time Health Top Hospitals across 9 Categories 2022', 'Best Multi Speciality Hospital by Time Health Survey 2021', 'India Healthcare Award for Best Hospital for Medical Tourism 2020', 'VCCircle Healthcare Award for Single Speciality Healthcare Entity 2013', 'Trailblazer in Robotic Surgeries'],
    expertise: ['15,000+ cardiac surgeries performed', '2,500+ joint replacements', '500+ Living Donor Liver Transplants (highest in India, 2nd in world)', 'Asia\'s First Bloodless Bone Marrow Transplant', 'India\'s first Air Ambulance launch 2013', 'CyberKnife Robotic Radiosurgery for brain, spine, prostate, liver tumors', 'Advanced MRI for prostate tumor diagnosis', 'Real-time MRI scans in Neurosciences', 'Minimally invasive cardiac surgeries', 'Open heart surgeries', 'Robotic surgeries in cardiology, urology, and gynaecology', '900+ skilled specialists'],
    infrastructure: ['2.1 million sq.ft facility - one of India\'s largest multi-specialty hospitals', '1600+ hospital beds', '1390+ operational suites', '270+ ICU beds', '40+ modular operation theatres with laminar air flow', 'Hybrid cath labs with advanced imaging and robotic arms', '256-Slice CT Scanner', '3.0 Tesla MRI', 'PET-CT imaging', 'CyberKnife Robotic Radiosurgery system', 'Advanced diagnostic technology', 'Real-time MRI scanning capability'],
    emergency: true,
    parking: true,
    featured: true,
  },
  {
    id: '17',
    name: 'Metro Hospital and Heart Institute',
    type: 'General Hospital',
    location: 'Sector 16 A, Faridabad (Delhi - NCR) - 121002',
    city: 'Faridabad',
    state: 'Haryana',
    rating: 4.8,
    reviewCount: 1680,
    beds: 450,
    established: 2002,
    image: '/doctor.png',
    description: 'Metro Hospital, Faridabad was established in 2002 and founded by Dr. Purshotam Lal (Padma Vibhushan, Padma Bhushan, and Dr. B C Roy National Awardee), one of the best cardiology surgeons in the country. Accredited with JCI certification, the hospital has a clear vision to provide the best services and treatment to patients from poor financial backgrounds at the most affordable cost. Dr. Neeraj Jain, a reputed Cardiologist and Cardiac Surgeon with immense expertise in Angioplasty, is among the distinguished specialists. The hospital is especially known for Cardiology, Neuroscience, Orthopedics, Centre for Liver and Digestive Diseases, Onco-surgeries, and Centre for Mother and Child. Equipped with advanced technology, Metro Hospital offers wide-ranging treatments in Preventive Cardiology, Interventional Cardiology, Electrophysiology, Cardiothoracic and Vascular Surgery. The hospital provides multilingual coordinators, painless labor with Epidural Analgesia, and is among the few centres in North India offering Endobronchial Ultrasound (EBUS), a minimally invasive diagnostic technique. With numerous prestigious awards including Best Multi Super Speciality Hospital 2024 and Lifetime Achievement Awards, Metro Hospital serves patients from all over the world.',
    shortDescription: 'Multi-specialty hospital with 450+ beds founded by Padma Vibhushan Dr. Purshotam Lal, JCI-accredited cardiac care excellence',
    specialties: ['Cardiac Sciences', 'Cancer Care', 'Gastroenterology', 'Hematology', 'Robotic Surgery', 'Organ Transplant', 'Neurosciences', 'Renal Sciences', 'Orthopedics and Joint Replacement', 'Paediatric and Neonatology', 'Obstetrics and Gynaecology', 'Preventive Cardiology', 'Interventional Cardiology', 'Electrophysiology', 'Cardiothoracic and Vascular Surgery', 'Liver and Digestive Diseases', 'Onco-surgeries'],
    facilities: ['Centre for Cardiac Sciences', 'Centre for Liver and Digestive Diseases', 'Centre for Mother and Child', '147 ICU Beds', 'Interventional Cardiology Unit', 'Electrophysiology Lab', 'Robotic Surgery', 'Endobronchial Ultrasound (EBUS)', 'Painless Labor and Epidural Analgesia', 'High-resolution Imaging Machines', 'Multilingual Coordinators', 'International Patient Services', 'Organ Transplant Unit', 'Neonatology Unit'],
    accreditations: ['JCI (Joint Commission International)', 'Best Multi Super Speciality Hospital by Healthcare Innovation Summit & Awards 2024', 'IISA Emerging Leader of the Year 2024', 'Dainik Jagran Healthcare Heroes Award 2024', 'Rising Stars of the Year 2023', 'Swasthya Ratan Award by Governor of Haryana 2023', 'Iconic National Award by IMA Delhi 2023', 'Lifetime Achievement Award by HIPE 3.0 2023', 'Excellence in Diabetes Healthcare Award 2023', 'ET Leadership Excellence Award 2023', 'Top 10 Hospitals of Delhi NCR 2022', 'Lifetime Achievement Award by Dainik Jagran Ayushman India 2021', 'Top 3 Hospital in Noida 2021', 'Best Cardiology Hospital 2017', 'Padma Vibhushan by President of India 2009', 'Dr. B.C Roy National Award 2004', 'Padma Bhushan by President of India 2003'],
    expertise: ['Founded by Padma Vibhushan Dr. Purshotam Lal', 'Dr. Neeraj Jain - renowned for Angioplasty expertise', 'Largest number of Angioplasties/Stentings by single operator in India', 'Advanced cardiac procedures', 'Preventive and interventional cardiology', 'Electrophysiology', 'Cardiothoracic and vascular surgery', 'Endobronchial Ultrasound (EBUS) - minimally invasive diagnostics', 'Painless labor with Epidural Analgesia', 'Robotic surgery', 'Organ transplantation', 'Liver and digestive disease treatment', 'Mother and child care', 'International patient care with transparent pricing'],
    infrastructure: ['8 acres campus', '450+ hospital beds', '147 ICU beds', 'State-of-the-art infrastructure designed for medical needs', 'Advanced cardiac cath labs', 'Electrophysiology laboratories', 'High-resolution imaging machines', 'Endobronchial Ultrasound (EBUS) facility', 'Robotic surgery systems', 'Neonatology unit', 'Modern operation theatres', 'International patient services', 'Multilingual coordination facilities'],
    emergency: true,
    parking: true,
    featured: true,
  },
  {
    id: '18',
    name: 'Nova IVF Fertility',
    type: 'Specialty Hospital',
    location: 'Palam Marg, Ground Floor, Building No. 2, Vasant Vihar, New Delhi - 110057',
    city: 'New Delhi',
    state: 'Delhi',
    rating: 4.8,
    reviewCount: 920,
    beds: 40,
    established: 2021,
    image: '/doctor.png',
    description: 'Nova IVF Fertility (NIF) is one of the leading healthcare fertility service providers in India, established in 2021. The centre offers a wide range of advanced treatments through Assisted Reproductive Technology (ART) with high-quality equipment. Nova IVF Fertility helps couples fight infertility issues and receive the best treatment under a trusted fertility centre. With 62 centres across 42 cities in India, NIF is among the leading centres with advanced ART qualifying global standards. The centre is committed to providing a complete range of fertility services including IUI, andrology, and advanced techniques like vitrification for egg/embryo preservation, embryoscope, and ERA (endometrial receptor array). Under the supervision of fertility experts, the chances of pregnancy improve even for patients who have lost hope. Nova is the most advanced IVF centre providing treatments like IMSI (intracytoplasmic morphologically-selected sperm injection) and ICSI (intracytoplasmic sperm injection), promising the best quality sperm to fertilize the egg. The Vasant Vihar centre provides complete care and comprehensive infertility management programs at one place, serving patients from Middle East Asia, Africa, and Fiji with international standards.',
    shortDescription: 'Leading fertility centre with 62 locations across 42 cities, specializing in advanced ART and international standard IVF treatments',
    specialties: ['Infertility Assessment Female', 'Infertility Assessment Male', 'Semen Analysis', 'Intra-uterine Insemination (IUI)', 'In-vitro Fertilisation (IVF)', 'Intracytoplasmic Sperm Injection (ICSI)', 'Pre-genetic Testing (PGT)', 'Testicular Sperm Aspiration (TESA)', 'Percutaneous Epididymal Sperm Aspiration (PESA)', 'Cryopreservation', 'Reproductive Genetics', 'Endoscopy', 'IMSI (Intracytoplasmic Morphologically-Selected Sperm Injection)'],
    facilities: ['IUI Services', 'Andrology Department', 'Vitrification for Egg/Embryo Preservation', 'Embryoscope', 'ERA (Endometrial Receptor Array)', 'IMSI Technology', 'ICSI Technology', 'Cryopreservation Unit', 'Reproductive Genetics Lab', 'Endoscopy Unit', 'Fellowship Programs', 'Nova Embryology Academy (NACET)'],
    accreditations: ['Silver for Outstanding IVF Brand (Metro) 2024', 'Gold for Outstanding Initiative for Public Awareness of Fertility Issues 2024', 'Silver for Outstanding IVF Chain 2024', 'Gold for Excellence in Reproductive and Endocrinology 2024 - Dr. Jayesh Amin', 'IVF Hall of Fame - Dr. Madhu Priya (Coimbatore) 2025', 'Integrated Team of the Year - West 2025', 'IVF Champion Brand of the Year 2025'],
    expertise: ['Advanced Assisted Reproductive Technology (ART) with global standards', '62 centres across 42 cities in India', 'IMSI (Intracytoplasmic Morphologically-Selected Sperm Injection)', 'ICSI (Intracytoplasmic Sperm Injection) with best quality sperm', 'Vitrification for egg/embryo preservation', 'Embryoscope technology', 'ERA (Endometrial Receptor Array)', 'Pre-genetic Testing (PGT)', 'Testicular and epididymal sperm aspiration (TESA, PESA)', 'International expertise from Middle East Asia, Africa, and Fiji', 'Fellowship programs in Reproductive Medicine and Embryology', 'Comprehensive infertility management'],
    infrastructure: ['62 centres across 42 cities in India', 'International standard ART facilities', 'Advanced vitrification technology', 'Embryoscope equipment', 'ERA technology', 'IMSI and ICSI labs', 'Cryopreservation facilities', 'Reproductive genetics laboratory', 'Nova Embryology Academy (NACET)', 'Fellowship training programs', 'Comprehensive infertility management centre', '10 km from airport (approx 18 min)'],
    emergency: false,
    parking: true,
    featured: true,
  },
];

export const cities = Array.from(new Set(hospitalsData.map(h => h.city))).sort();
