import { Doctor } from './types';

export const doctorsData: Doctor[] = [
  {
    id: '1',
    name: 'Dr. Omar Karim',
    specialty: 'Cardiologist',
    rating: 4.9,
    image: '/doctor.png',
    bio: 'Dr. Omar Siddiqui is an experienced cardiologist dedicated to diagnosing and treating complex heart conditions with precision.',
    category: 'Cardiologist',
  },
  {
    id: '2',
    name: 'Dr. Amira Siddiqui',
    specialty: 'Cardiologist',
    rating: 4.9,
    image: '/doctor-img 1.png',
    bio: 'Dr. Amira Siddiqui is an experienced cardiologist dedicated to diagnosing and treating complex heart conditions with precision.',
    category: 'Cardiologist',
  },
  {
    id: '3',
    name: 'Dr. Esther Howard',
    specialty: 'Cardiologist',
    rating: 4.8,
    image: '/doctor-img2 1.png',
    bio: 'Dr. Amira Siddiqui is an experienced cardiologist dedicated to diagnosing and treating complex heart conditions with precision.',
    category: 'Cardiologist',
  },
  {
    id: '4',
    name: 'Dr. Sarah Johnson',
    specialty: 'Neurologist',
    rating: 4.9,
    image: '/doctor.png',
    bio: 'Dr. Sarah Johnson specializes in neurological disorders with over 15 years of experience in treating complex conditions.',
    category: 'Neurologist',
  },
  {
    id: '5',
    name: 'Dr. Michael Chen',
    specialty: 'Orthopedic',
    rating: 4.7,
    image: '/doctor.png',
    bio: 'Dr. Michael Chen is an expert orthopedic surgeon specializing in joint replacement and sports medicine.',
    category: 'Orthopedic',
  },
  {
    id: '6',
    name: 'Dr. Emily Davis',
    specialty: 'Urologist',
    rating: 4.8,
    image: '/doctor-img 1.png',
    bio: 'Dr. Emily Davis provides comprehensive urological care with a focus on minimally invasive procedures.',
    category: 'Urologist',
  },
  {
    id: '7',
    name: 'Dr. Robert Martinez',
    specialty: 'Orthopedic',
    rating: 4.9,
    image: '/doctor.png',
    bio: 'Dr. Robert Martinez specializes in orthopedic surgery with expertise in sports injuries.',
    category: 'Orthopedic',
  },
  {
    id: '8',
    name: 'Dr. Lisa Thompson',
    specialty: 'Neurologist',
    rating: 4.7,
    image: '/doctor-img2 1.png',
    bio: 'Dr. Lisa Thompson is a neurologist with extensive experience in treating stroke and brain disorders.',
    category: 'Neurologist',
  },
  {
    id: '9',
    name: 'Dr. James Wilson',
    specialty: 'Cardiologist',
    rating: 4.8,
    image: '/doctor.png',
    bio: 'Dr. James Wilson provides comprehensive cardiac care including preventive cardiology.',
    category: 'Cardiologist',
  },
  {
    id: '10',
    name: 'Dr. Patricia Brown',
    specialty: 'Urologist',
    rating: 4.9,
    image: '/doctor-img 1.png',
    bio: 'Dr. Patricia Brown specializes in urological oncology and minimally invasive techniques.',
    category: 'Urologist',
  },
  {
    id: '11',
    name: 'Dr. David Lee',
    specialty: 'Orthopedic',
    rating: 4.6,
    image: '/doctor.png',
    bio: 'Dr. David Lee is an orthopedic surgeon focusing on pediatric orthopedics.',
    category: 'Orthopedic',
  },
  {
    id: '12',
    name: 'Dr. Jennifer Garcia',
    specialty: 'Cardiologist',
    rating: 4.9,
    image: '/doctor-img2 1.png',
    bio: 'Dr. Jennifer Garcia specializes in heart failure management and cardiac transplantation.',
    category: 'Cardiologist',
  },
  {
    id: '13',
    name: 'Dr. Thomas Anderson',
    specialty: 'Neurologist',
    rating: 4.8,
    image: '/doctor.png',
    bio: 'Dr. Thomas Anderson focuses on movement disorders including Parkinson\'s disease.',
    category: 'Neurologist',
  },
  {
    id: '14',
    name: 'Dr. Maria Rodriguez',
    specialty: 'Urologist',
    rating: 4.7,
    image: '/doctor-img 1.png',
    bio: 'Dr. Maria Rodriguez provides expert care in female urology and pelvic floor disorders.',
    category: 'Urologist',
  },
  {
    id: '15',
    name: 'Dr. Christopher White',
    specialty: 'Cardiologist',
    rating: 4.9,
    image: '/doctor.png',
    bio: 'Dr. Christopher White specializes in electrophysiology and cardiac rhythm management.',
    category: 'Cardiologist',
  },
  {
    id: '16',
    name: 'Dr. Susan Taylor',
    specialty: 'Orthopedic',
    rating: 4.8,
    image: '/doctor-img2 1.png',
    bio: 'Dr. Susan Taylor is an orthopedic specialist focusing on hand surgery.',
    category: 'Orthopedic',
  },
  {
    id: '17',
    name: 'Dr. Daniel Moore',
    specialty: 'Neurologist',
    rating: 4.7,
    image: '/doctor.png',
    bio: 'Dr. Daniel Moore specializes in epilepsy treatment and neurophysiological monitoring.',
    category: 'Neurologist',
  },
  {
    id: '18',
    name: 'Dr. Nancy Clark',
    specialty: 'Cardiologist',
    rating: 4.9,
    image: '/doctor-img 1.png',
    bio: 'Dr. Nancy Clark provides comprehensive care in preventive cardiology.',
    category: 'Cardiologist',
  },
];
