import { Treatment } from './types';

export const treatmentsData: Treatment[] = [
  {
    id: '1',
    title: 'Cardiac Catheterization',
    category: 'Cardiology',
    description: 'A minimally invasive procedure to diagnose and treat cardiovascular conditions. Our state-of-the-art cardiac catheterization lab uses advanced imaging technology to guide thin, flexible tubes through blood vessels to the heart. This procedure helps identify blockages, measure pressure, and assess heart function with precision and safety.',
    shortDescription: 'Minimally invasive heart diagnostic and treatment procedure',
    image: '/doctor.png',
    duration: '1-2 hours',
    price: '$3,500 - $8,000',
    featured: true,
    benefits: [
      'Accurate diagnosis of heart conditions',
      'Minimally invasive with faster recovery',
      'Real-time imaging and assessment',
      'Can treat blockages during same procedure',
      'Lower risk compared to open surgery',
    ],
    procedures: [
      'Patient preparation and local anesthesia',
      'Catheter insertion through blood vessel',
      'Navigation to heart using X-ray guidance',
      'Diagnostic imaging and measurements',
      'Treatment if necessary (angioplasty/stent)',
      'Recovery and monitoring',
    ],
  },
  {
    id: '2',
    title: 'Joint Replacement Surgery',
    category: 'Orthopedics',
    description: 'Advanced joint replacement procedures using cutting-edge prosthetic technology and minimally invasive surgical techniques. Our orthopedic surgeons specialize in hip, knee, and shoulder replacements, providing customized solutions to restore mobility and eliminate chronic pain. We use the latest materials and computer-assisted surgery for optimal outcomes.',
    shortDescription: 'Restore mobility with advanced joint replacement',
    image: '/doctor-img 1.png',
    duration: '2-3 hours',
    price: '$15,000 - $35,000',
    featured: true,
    benefits: [
      'Pain relief and improved mobility',
      'Long-lasting prosthetic joints',
      'Customized implant fitting',
      'Minimally invasive techniques',
      'Comprehensive rehabilitation program',
    ],
    procedures: [
      'Pre-operative assessment and planning',
      'Surgical removal of damaged joint',
      'Precise implant positioning',
      'Computer-assisted alignment',
      'Post-operative care and monitoring',
      'Physical therapy and rehabilitation',
    ],
  },
  {
    id: '3',
    title: 'Brain Tumor Surgery',
    category: 'Neurology',
    description: 'Expert neurosurgical treatment for brain tumors using advanced techniques including microsurgery, neuronavigation, and intraoperative monitoring. Our neurosurgery team combines precision technology with extensive experience to safely remove tumors while preserving critical brain functions. We offer comprehensive care from diagnosis through recovery.',
    shortDescription: 'Advanced neurosurgical brain tumor treatment',
    image: '/doctor-img2 1.png',
    duration: '4-8 hours',
    price: '$50,000 - $100,000',
    featured: true,
    benefits: [
      'Precision tumor removal',
      'Brain function preservation',
      'Advanced imaging guidance',
      'Minimized surgical trauma',
      'Multidisciplinary care team',
    ],
    procedures: [
      'Comprehensive neurological evaluation',
      'Advanced imaging and mapping',
      'Craniotomy and tumor access',
      'Microsurgical tumor removal',
      'Intraoperative monitoring',
      'Intensive care and recovery',
    ],
  },
  {
    id: '4',
    title: 'Kidney Stone Removal',
    category: 'Urology',
    description: 'Modern minimally invasive treatments for kidney stones including laser lithotripsy, ureteroscopy, and extracorporeal shock wave lithotripsy (ESWL). Our urologists use the latest technology to safely and effectively remove stones of all sizes, providing rapid pain relief and preventing future complications.',
    shortDescription: 'Minimally invasive kidney stone treatment',
    image: '/doctor.png',
    duration: '1-3 hours',
    price: '$5,000 - $12,000',
    featured: false,
    benefits: [
      'Quick pain relief',
      'Minimally invasive procedures',
      'No major incisions required',
      'Fast recovery time',
      'Prevention guidance included',
    ],
    procedures: [
      'Diagnostic imaging and stone analysis',
      'Procedure selection based on stone size',
      'Minimally invasive stone fragmentation',
      'Stone removal or passage',
      'Post-procedure monitoring',
      'Follow-up care and prevention plan',
    ],
  },
  {
    id: '5',
    title: 'Laparoscopic Surgery',
    category: 'General Surgery',
    description: 'Minimally invasive surgical procedures performed through small incisions using specialized instruments and camera systems. Our general surgeons are experts in laparoscopic techniques for gallbladder removal, hernia repair, appendectomy, and other abdominal procedures, resulting in less pain, smaller scars, and faster recovery.',
    shortDescription: 'Minimally invasive surgical procedures',
    image: '/doctor-img 1.png',
    duration: '1-4 hours',
    price: '$8,000 - $20,000',
    featured: true,
    benefits: [
      'Smaller incisions and scars',
      'Reduced post-operative pain',
      'Faster recovery time',
      'Lower infection risk',
      'Shorter hospital stay',
    ],
    procedures: [
      'Pre-operative preparation',
      'Small incision creation',
      'Camera and instrument insertion',
      'Surgical procedure performance',
      'Closure and recovery',
      'Same-day or next-day discharge',
    ],
  },
  {
    id: '6',
    title: 'Coronary Artery Bypass',
    category: 'Cardiology',
    description: 'Life-saving open-heart surgery to improve blood flow to the heart muscle. Our cardiac surgeons perform both traditional and minimally invasive bypass procedures, creating new routes around blocked arteries using healthy blood vessels from other parts of the body. Comprehensive cardiac rehabilitation ensures optimal recovery.',
    shortDescription: 'Heart bypass surgery for blocked arteries',
    image: '/doctor-img2 1.png',
    duration: '3-6 hours',
    price: '$70,000 - $150,000',
    featured: false,
    benefits: [
      'Improved heart blood flow',
      'Relief from chest pain',
      'Reduced heart attack risk',
      'Extended life expectancy',
      'Enhanced quality of life',
    ],
    procedures: [
      'Comprehensive cardiac evaluation',
      'Surgical planning and preparation',
      'Chest opening and heart access',
      'Bypass graft creation',
      'Heart-lung machine management',
      'Intensive post-operative care',
    ],
  },
  {
    id: '7',
    title: 'Spinal Fusion Surgery',
    category: 'Orthopedics',
    description: 'Surgical procedure to permanently connect two or more vertebrae in the spine, eliminating motion between them. Using advanced techniques including minimally invasive approaches, our spine surgeons treat conditions like degenerative disc disease, spinal stenosis, and scoliosis, providing lasting pain relief and stability.',
    shortDescription: 'Spine stabilization and pain relief surgery',
    image: '/doctor.png',
    duration: '3-5 hours',
    price: '$30,000 - $80,000',
    featured: false,
    benefits: [
      'Chronic pain relief',
      'Spinal stability restoration',
      'Nerve pressure reduction',
      'Improved posture and function',
      'Long-term solution',
    ],
    procedures: [
      'Detailed spinal imaging',
      'Surgical approach planning',
      'Bone graft preparation',
      'Vertebrae fusion',
      'Hardware implantation',
      'Rehabilitation program',
    ],
  },
  {
    id: '8',
    title: 'Stroke Treatment',
    category: 'Neurology',
    description: 'Emergency and comprehensive stroke care including clot-busting medications, mechanical thrombectomy, and neurorehabilitation. Our stroke team provides rapid response 24/7, using advanced imaging and treatment protocols to minimize brain damage and maximize recovery potential. Time-critical intervention saves lives and function.',
    shortDescription: 'Emergency stroke intervention and care',
    image: '/doctor-img 1.png',
    duration: '1-6 hours',
    price: '$20,000 - $60,000',
    featured: true,
    benefits: [
      'Rapid intervention saves brain tissue',
      'Minimizes long-term disability',
      '24/7 stroke team availability',
      'Advanced clot removal technology',
      'Comprehensive rehabilitation',
    ],
    procedures: [
      'Immediate assessment and imaging',
      'Rapid treatment decision',
      'Clot-busting medication or surgery',
      'Intensive monitoring',
      'Neurological assessment',
      'Rehabilitation planning',
    ],
  },
  {
    id: '9',
    title: 'Prostate Treatment',
    category: 'Urology',
    description: 'Comprehensive treatment options for enlarged prostate and prostate cancer including minimally invasive procedures, robotic surgery, and radiation therapy. Our urologists provide personalized care plans using the latest technology to treat prostate conditions while preserving quality of life and function.',
    shortDescription: 'Advanced prostate care and treatment',
    image: '/doctor-img2 1.png',
    duration: '2-4 hours',
    price: '$10,000 - $40,000',
    featured: false,
    benefits: [
      'Symptom relief',
      'Function preservation',
      'Multiple treatment options',
      'Minimally invasive approaches',
      'Personalized care plans',
    ],
    procedures: [
      'Comprehensive prostate evaluation',
      'Treatment option consultation',
      'Procedure performance',
      'Post-treatment monitoring',
      'Follow-up care',
      'Quality of life assessment',
    ],
  },
  {
    id: '10',
    title: 'Hernia Repair',
    category: 'General Surgery',
    description: 'Expert surgical repair of inguinal, umbilical, hiatal, and ventral hernias using both open and laparoscopic techniques. Our surgeons use the latest mesh materials and tension-free repair methods to ensure strong, lasting results with minimal recurrence risk and faster return to normal activities.',
    shortDescription: 'Surgical hernia correction and repair',
    image: '/doctor.png',
    duration: '1-2 hours',
    price: '$5,000 - $15,000',
    featured: false,
    benefits: [
      'Pain and discomfort relief',
      'Prevention of complications',
      'Quick recovery time',
      'Low recurrence rate',
      'Minimal scarring',
    ],
    procedures: [
      'Physical examination',
      'Surgical approach selection',
      'Hernia reduction',
      'Mesh placement if needed',
      'Tissue reinforcement',
      'Same-day discharge often possible',
    ],
  },
];
