
import { Treatment } from './types';
import cardiology from "@/public/cardio.jpeg"
import Bone from "@/public/Bone Marrow Transplant.jpg"
import aoratic from "@/public/aoratic.jpeg"
import congenital from "@/public/congenital.jpg"
import gastro from "@/public/gastro.jpg"
import gyna from "@/public/gyna.jpg"
import ivf from "@/public/ivf.jpg"
import Neurology from "@/public/Neurology.webp"
import Oncology from "@/public/Oncology.jpeg"









export const treatmentsData: Treatment[] = [
  {
    id: "1",
    slug: "bone-marrow-transplant",
    title: "Bone Marrow Transplant",
    category: "Stem Cell Therapy",
    description: `# Bone Marrow Transplant`,
    overview: `Bone Marrow Transplant is a medical condition that treats unhealthy blood cells. A Bone Marrow Transplant in India is also known as a stem cell transplant. The treatment involves replacing bone marrow that does not develop enough healthy blood cells, also the transplant helps to produce healthy blood forming stem cells into the body. The bone marrow transplant treatment is performed when the bone marrow does not work properly or is unable to produce healthy blood cells.`,
    types: `- **Allogeneic stem cell transplant:** The transplant used from the donor is known as allogeneic transplant.\n- **Autologous stem cell transplant:** The cells that are used for the transplant are consumed from your own body that is called autologous transplant.`,
    purpose: `- The bone marrow transplant treatment allows high dose chemotherapy and radiation therapy to be infused safely by replacing or rescuing the affected bone marrow.\n- Removes the cells that are not in use with the new stem cells.\n- Infuses new stem cells and kills the cancer cells directly.`,
    diseasesTreated: `- Acute leukemia\n- Adrenoleukodystrophy\n- Aplastic anemia\n- Bone marrow failure syndromes\n- Chronic leukemia\n- Hemoglobinopathies\n- Hodgkin's lymphoma\n- Immune deficiencies\n- Inborn errors of metabolism\n- Multiple myeloma\n- Myelodysplastic syndromes\n- Neuroblastoma\n- Non-Hodgkin's lymphoma\n- Plasma cell disorders\n- POEMS syndrome\n- Primary amyloidosis`,
    risks: `- Graft versus host disease (GVHD) that only affects the people with allogeneic transplant\n- Stem cell failure\n- Organ damage\n- Infection\n- Cataracts\n- Infertility\n- New cancers\n- Death`,
    gvhd: `GVHD is a type of risk that can occur any time after the transplant, especially in allogeneic transplants. It happens when donor stem cells attack the recipient's tissues and organs.\n- **Acute GVHD:** Mostly takes place during the first month of the transplant.\n- **Chronic GVHD:** Hits many organs and mostly occurs later.`,
    gvhdSymptoms: `- Joint pain\n- Muscle pain\n- Breathing problem\n- Continuous cough\n- Scarring under the skin or skin stiffness\n- Rash\n- Yellowing of the skin and eye whites\n- Dry mouth\n- Mouth sores\n- Diarrhea\n- Nausea\n- Vomiting`,
    preTransplant: `Tests and procedures are conducted to diagnose and prepare for the transplant, including insertion of a central line for infusions. Delhi offers affordable and advanced procedures for faster healing.`,
    autologous: `In autologous transplants, stem cells are collected from your own blood using apheresis after growth factor injections. The cells are then frozen for later use.`,
    conditioning: `After evaluation, conditioning (chemotherapy/radiation) is performed to kill cancer cells, prepare the bone marrow, and control the immune system. Risks include nausea, vomiting, diarrhea, hair loss, mouth sores, ulcers, infection, bleeding, infertility, anemia, fatigue, cataracts, and organ failure.`,
    summary: `Bone Marrow Transplant helps cure many diseases, aiming to extend life, improve health, and control disease spread. Outcomes depend on individual conditions and side effects. Top specialists in India are globally recognized for their expertise and advanced hospital facilities.`,
    shortDescription: "Advanced treatment for blood and bone marrow diseases using stem cell transplantation",
    image: Bone,
    duration: "Varies by transplant type and patient condition",
    price: "Affordable compared to Western countries; varies by procedure complexity",
    featured: true,
    benefits: [
      "Cures or controls many blood cancers and disorders",
      "Access to advanced stem cell and transplant technology",
      "Multidisciplinary care from transplant specialists",
      "Internationally recognized expertise and facilities"
    ],
    procedures: [
      "Pre-transplant evaluation and central line placement",
      "Stem cell harvesting (apheresis or donor collection)",
      "Conditioning (chemotherapy/radiation)",
      "Stem cell infusion",
      "Post-transplant monitoring and supportive care",
      "GVHD management and long-term follow-up"
    ]
  },
  {
    id: "2",
    slug: "cardiology",
    title: "Cardiology",
    category: "Cardiology",
    description: `# Cardiology`,
    overview: `Cardiology is the medical specialty that deals with diseases of the heart and blood vessels. It includes problems related to the heart muscle, heart arteries, heart valves, heart rhythm, and major blood vessels. In India, cardiology care is provided in structured hospital departments where doctors use detailed heart tests to clearly understand each patient's condition. Treatment is planned step by step and may include medicines, procedures, or surgery, with continued follow-up to support recovery and long-term heart care.`,
    types: `- **Preventive cardiology:** Heart risk assessment, screening, lifestyle guidance, metabolic care, and long-term prevention of cardiovascular disease.\n- **Clinical cardiology:** Evaluation of heart-related symptoms, diagnostic testing, and ongoing medical management.\n- **Interventional cardiology:** Image-guided catheter-based procedures for diagnosis and targeted treatment.\n- **Electrophysiology and device therapy:** Evaluation and management of heart rhythm and conduction disorders, including implantable devices.\n- **Structural heart care:** Assessment and correction of heart valve disease and congenital structural abnormalities.\n- **Cardiac surgery:** Open and minimally invasive surgical correction of coronary, valvular, congenital, and aortic diseases.\n- **Heart failure and advanced cardiac care:** Management of reduced or advanced cardiac function.\n- **Cardiac rehabilitation:** Recovery support, functional improvement, and secondary prevention programs.`,
    purpose: `To prevent, diagnose, treat, and manage a wide range of cardiovascular diseases, improving heart function, alleviating symptoms, preventing complications, and enhancing quality of life.`,
    diseasesTreated: `- **Coronary and vascular conditions:** Chest pain syndromes, coronary artery disease, heart attack, peripheral arterial disease, aortic disorders.\n- **Heart muscle and pumping disorders:** Heart failure, weak heart pumping function, inflammatory heart muscle disease.\n- **Heart rhythm and conduction disorders:** Atrial fibrillation, abnormally fast or slow heart rhythms, ventricular rhythm disorders.\n- **Heart valve and structural disorders:** Narrowed or leaking heart valves, degenerative, rheumatic, and infective valve disease.\n- **Congenital heart diseases:** Abnormal heart connections, holes in heart walls, congenital valve problems.\n- **Inflammatory and infiltrative heart disorders:** Myocarditis, pericardial disease, endocarditis.\n- **Lung-related and pressure-related heart disorders:** Pulmonary hypertension, right-sided heart failure.`,
    risks: `Varies by specific condition and procedure; may include bleeding, infection, arrhythmias, blood clots, stroke, heart attack, or reactions to medications or contrast dye.`,
    summary: `Cardiology in India offers comprehensive, multidisciplinary care with advanced diagnostics, interventional procedures, and cardiac surgery. International patients benefit from high-quality, cost-effective treatment, experienced specialists, and streamlined support services.`,
    shortDescription: "Comprehensive diagnosis and treatment of heart and blood vessel diseases",
    image: cardiology,
    duration: "Varies from outpatient consultations to complex surgeries",
    price: "Cost-effective; varies by procedure complexity",
    featured: true,
    benefits: [
      "Advanced diagnostic imaging and testing",
      "Minimally invasive interventional procedures",
      "Expert cardiac surgical teams",
      "Integrated rehabilitation and long-term care"
    ],
    procedures: [
      "Clinical consultation and risk assessment",
      "Diagnostic testing (ECG, Echo, Stress Test, Angiography)",
      "Medical management and optimization",
      "Interventional procedures (angioplasty, stenting, ablation)",
      "Cardiac surgery (CABG, valve repair/replacement)",
      "Rehabilitation and follow-up care"
    ]
  },
  {
    id: "3",
    slug: "aortic-surgery",
    title: "Aortic Surgery",
    category: "Cardiac Surgery",
    description: `# Clinical Guide to Aortic Surgery in India`,
    overview: `The aorta is the body's main and largest artery, carrying oxygen-rich blood from the heart to all vital organs. When the aorta becomes weakened, enlarged, or damaged due to disease, injury, or age-related changes, it can seriously affect blood circulation and overall cardiovascular health. Aortic surgery includes carefully planned procedures used to repair or replace affected sections of the aorta, either through open surgical techniques or minimally invasive endovascular approaches, based on detailed specialist evaluation.`,
    types: `- **Open aortic surgery:** Traditional surgical approach for complex repairs.\n- **Endovascular aortic repair (EVAR/TEVAR):** Minimally invasive catheter-based procedures.\n- **Hybrid approaches:** Combination of surgical and catheter-based techniques.`,
    purpose: `To repair or replace diseased sections of the aorta (aneurysms, dissections, trauma) to prevent rupture, restore normal blood flow, and reduce risk of life-threatening complications.`,
    diseasesTreated: `- Aortic aneurysms (thoracic, abdominal)\n- Aortic dissections\n- Aortic trauma\n- Aortic valve disease requiring root replacement\n- Connective tissue disorders affecting the aorta (e.g., Marfan syndrome)`,
    risks: `- Bleeding\n- Infection\n- Stroke\n- Kidney injury\n- Spinal cord injury (risk of paralysis)\n- Graft complications\n- Heart attack\n- Death`,
    summary: `Aortic surgery in India is performed at leading cardiac centers adhering to international safety protocols. It offers substantial cost advantages compared to Western countries while maintaining high-quality outcomes. A structured pathway supports international patients from remote consultation to post-discharge coordination.`,
    shortDescription: "Surgical repair or replacement of the body's main artery",
    image: aoratic,
    duration: "Several hours for surgery; recovery varies",
    price: "Cost-effective compared to Western countries",
    featured: false,
    benefits: [
      "Prevents life-threatening aortic rupture",
      "Restores normal blood flow to vital organs",
      "Minimally invasive endovascular options available",
      "JCI/NABH accredited high-quality centers"
    ],
    procedures: [
      "Diagnostic imaging (CT angiography, MRI, Echocardiography)",
      "Pre-operative evaluation and planning",
      "Surgical procedure (open or endovascular)",
      "Intensive care unit recovery",
      "Post-operative monitoring and rehabilitation",
      "Long-term surveillance imaging"
    ]
  },
  {
    id: "4",
    slug: "congenital-heart-defect-repair",
    title: "Congenital Heart Defect Repair",
    category: "Cardiac Surgery",
    description: `# Clinical Guide to Congenital Heart Defect Repair in India`,
    overview: `A Congenital Heart Defect (CHD) refers to one or more structural abnormalities of the heart present at birth. They may affect the heart walls, valves, or blood vessels, and can change how blood flows through the heart and body. CHDs range from simple conditions that may only require monitoring to complex defects that may need long-term clinical management and, in some cases, surgical repair. Advances in pediatric cardiac surgery and interventional cardiology have transformed outcomes for children born with heart defects. Many children who receive appropriate treatment go on to live full, active lives. India has developed specialized pediatric cardiac centers with expertise in treating the full spectrum of congenital heart conditions.`,
    types: `- **Catheter-based interventions:** Minimally invasive techniques to close holes, widen narrow valves, or place devices.\n- **Surgical repair:** Open-heart surgery or minimally invasive techniques to correct structural abnormalities.\n- **Clinical management:** Monitoring, symptom control, and supportive therapies for mild conditions or pre/post-procedure care.`,
    purpose: `To correct structural heart abnormalities, restore normal blood flow, prevent complications, and enable children to lead healthy, active lives.`,
    diseasesTreated: `- Atrial Septal Defect (ASD)\n- Ventricular Septal Defect (VSD)\n- Patent Ductus Arteriosus (PDA)\n- Tetralogy of Fallot\n- Transposition of the Great Arteries\n- Coarctation of the Aorta\n- Congenital valve disorders (e.g., pulmonary stenosis, aortic stenosis)\n- Complex single ventricle defects`,
    risks: `- Bleeding\n- Infection\n- Arrhythmias\n- Blood clots\n- Stroke\n- Heart block requiring pacemaker\n- Need for reoperation\n- Death`,
    summary: `India offers specialized pediatric cardiac centers with evidence-based protocols for congenital heart defect repair. Treatment is tailored to the specific defect and patient's health. International patients benefit from a regulated pathway including e-Medical Visa support, pre-arrival coordination, and continuity of care plans.`,
    shortDescription: "Surgical or catheter-based correction of heart defects present from birth",
    image: congenital,
    duration: "Varies from short procedures to complex multi-stage surgeries",
    price: "Transparent pricing based on clinical complexity",
    featured: false,
    benefits: [
      "Corrects abnormal heart structure and blood flow",
      "Enables normal growth and development",
      "Minimally invasive catheter options for eligible defects",
      "Multidisciplinary pediatric cardiac team"
    ],
    procedures: [
      "Diagnostic evaluation (Echocardiogram, ECG, Cardiac MRI/Cath)",
      "Multidisciplinary team planning",
      "Surgical repair or catheter intervention",
      "Post-operative Pediatric ICU care",
      "Recovery and rehabilitation",
      "Long-term cardiac follow-up"
    ]
  },
  {
    id: "5",
    slug: "gastroenterology",
    title: "Gastroenterology",
    category: "Gastroenterology",
    description: `# Gastroenterology`,
    overview: `Gastroenterology is a field of medicine that diagnoses and treats the digestive system's function and diseases. It deals with severe diseases related to the digestive system such as the esophagus, stomach, liver, pancreas, intestine, gallbladder and bile ducts. A digestive system is an important part of the body that plays an important role for good health and well being. Any kind of discomfort in the digestive system can lead to medical attention. Top Gastroenterologists in India have a global exposure in their field. They have extreme experience in treating or diagnosing a wide variety of digestive issues from mild to severe.`,
    types: `- **Diagnostic endoscopy:** Upper GI endoscopy, colonoscopy.\n- **Therapeutic endoscopy:** Polyp removal, stricture dilation, stent placement.\n- **Hepatology:** Management of liver diseases.\n- **Pancreatology:** Management of pancreatic disorders.\n- **Motility disorders:** Management of esophageal and intestinal motility issues.`,
    purpose: `To diagnose, treat, and manage disorders of the gastrointestinal tract and associated organs, relieving symptoms, treating disease, and improving digestive health and nutrition.`,
    diseasesTreated: `- Gastroesophageal Reflux Disease (GERD)\n- Irritable Bowel Syndrome (IBS)\n- Inflammatory Bowel Disease (IBD: Crohn's, Ulcerative Colitis)\n- Peptic ulcer disease\n- Gastric and esophageal cancers\n- Colorectal polyps and cancer\n- Pancreatitis and pancreatic cancer\n- Hepatitis, cirrhosis, fatty liver disease\n- Gallstones and biliary tract disease\n- Celiac disease\n- Achalasia\n- Barrett's esophagus`,
    risks: `Varies by procedure; endoscopic procedures carry risks of bleeding, perforation, infection, or sedation-related complications.`,
    summary: `Gastroenterology treatment in India is performed with utmost care and excellence. Hospitals are equipped with advanced technology, accredited (NABH, NABL, JCI), and staffed by skilled specialists. International patients receive comprehensive services including visa assistance, accommodation, and interpreter services.`,
    shortDescription: "Diagnosis and treatment of digestive system disorders",
    image: gastro,
    duration: "Outpatient to inpatient care depending on condition",
    price: "Affordable for international patients",
    featured: false,
    benefits: [
      "Comprehensive care for entire GI tract and accessory organs",
      "Advanced diagnostic and therapeutic endoscopy",
      "Expert management of complex liver and pancreatic diseases",
      "Multidisciplinary approach including nutrition support"
    ],
    procedures: [
      "Clinical consultation and history review",
      "Diagnostic imaging (Ultrasound, CT, MRI)",
      "Endoscopic procedures (Gastroscopy, Colonoscopy, ERCP)",
      "Biopsy and histopathological analysis",
      "Medical management (medications, diet plans)",
      "Surgical referral if required"
    ]
  },
  {
    id: "6",
    slug: "gynaecology",
    title: "Gynaecology",
    category: "Gynaecology",
    description: `# Understanding Gynaecology`,
    overview: `Gynaecology is a medical condition that treats the female reproductive system. Gynecology is also responsible for conceiving pregnancy, females who are not able to conceive naturally are somehow connected to issues in their reproductive system. Gynecology in India treats female reproductive health issues through both the procedure that is medicine and surgical. Some of the issues like hormonal imbalance, gynaecological illness can be treated with medicine, but some pharmacological issues like cancers, fibroids need surgical attention. The main parts of the body that come under gynaecology are the uterus, ovaries, vagina and breasts. The initial problems start from puberty through menopause that also covers reproductive issues, sexual health and pregnancy.`,
    types: `- **General gynaecology:** Routine care, screenings, menstrual disorders.\n- **Reproductive endocrinology & infertility:** Management of infertility, PCOS, hormonal disorders.\n- **Gynaecological oncology:** Diagnosis and treatment of cancers of the reproductive system.\n- **Urogynaecology:** Treatment of pelvic floor disorders, urinary incontinence.\n- **Minimally invasive gynaecological surgery:** Laparoscopic and robotic surgeries.`,
    purpose: `To maintain and restore health of the female reproductive system, manage menstrual and hormonal disorders, treat infections and cancers, support fertility, and care for women through all life stages.`,
    diseasesTreated: `- Menstrual disorders (heavy bleeding, irregular periods, amenorrhea)\n- Polycystic Ovary Syndrome (PCOS/PCOD)\n- Endometriosis\n- Uterine fibroids\n- Ovarian cysts\n- Pelvic inflammatory disease (PID)\n- Pelvic organ prolapse\n- Gynecological cancers (cervical, ovarian, uterine, vulvar)\n- Female infertility\n- Sexually transmitted infections (STIs)\n- Menopausal symptoms and osteoporosis\n- Pregnancy-related conditions (gestational diabetes, hypertension, etc.)`,
    risks: `Varies by procedure; surgical risks include bleeding, infection, damage to surrounding organs, anesthesia risks, and scarring.`,
    summary: `Gynaecology in India offers a vast range of diagnostic and therapeutic procedures performed by experienced specialists. Hospitals provide advanced minimally invasive and robotic surgical options, comprehensive cancer care, and fertility treatments, all within accredited facilities with international patient support services.`,
    shortDescription: "Comprehensive care for the female reproductive system",
    image: gyna,
    duration: "Varies from outpatient visits to major surgeries",
    price: "Varies by condition and procedure",
    featured: false,
    benefits: [
      "Complete reproductive health care from adolescence to menopause",
      "Advanced laparoscopic and robotic surgical techniques",
      "Fertility treatment and reproductive endocrinology",
      "Comprehensive cancer screening and oncology care"
    ],
    procedures: [
      "Clinical examination and Pap test/HPV screening",
      "Diagnostic imaging (Ultrasound, Hysteroscopy)",
      "Medical management (hormonal therapy, antibiotics)",
      "Minimally invasive surgery (Laparoscopy, Hysteroscopy)",
      "Major surgical procedures (Hysterectomy, Myomectomy, Oophorectomy)",
      "Fertility treatments (IUI, IVF coordination)",
      "Cancer treatment (surgery, chemotherapy, radiation)"
    ]
  },
  {
    id: "7",
    slug: "in-vitro-fertilization-ivf",
    title: "In-Vitro Fertilization (IVF)",
    category: "IVF",
    description: `# In-Vitro Fertilization (IVF)`,
    overview: `In-Vitro Fertilization, also commonly known as IVF, is a medical treatment that treats infertility. Infertility is a condition that prevents a person from conceiving pregnancy. IVF in India is gaining popularity day by day, as the couples who are trying to conceive pregnancy from the long run, but are unable to conceive IVF treatment is like a ray of hope. There can be several reasons for infertility, before considering any treatment it is important to identify and diagnose the cause of infertility. The IVF is a complex series of procedures where mature eggs are extracted from the ovaries and are fertilized with the sperm in the laboratory. Once the eggs are fertilized, they are known as embryos. When the embryo is formed they are placed back in the uterus where babies are developed. A single cycle of IVF takes about 2 to 3 weeks to complete. IVF in Delhi is considered to be one of the best treatments for infertility issues.`,
    types: `- **Conventional IVF:** Eggs and sperm are mixed together in a lab dish.\n- **ICSI (Intracytoplasmic Sperm Injection):** A single sperm is injected directly into an egg.\n- **Donor egg/sperm/embryo IVF:** Using donor genetic material.\n- **Frozen embryo transfer (FET):** Using previously frozen embryos.\n- **PGT (Preimplantation Genetic Testing):** Testing embryos for genetic disorders before transfer.`,
    purpose: `To help individuals and couples achieve pregnancy when natural conception is not possible due to various medical reasons such as blocked tubes, male factor infertility, ovulation disorders, endometriosis, unexplained infertility, or genetic concerns.`,
    diseasesTreated: `Primary and secondary infertility caused by:\n- Damaged or blocked fallopian tubes\n- Ovulation disorders\n- Endometriosis\n- Uterine fibroids\n- Male factor infertility (low sperm count, poor motility/morphology)\n- Unexplained infertility\n- Genetic disorders requiring PGT\n- Fertility preservation for medical reasons (e.g., prior to cancer treatment)`,
    risks: `- Ovarian hyperstimulation syndrome (OHSS)\n- Multiple pregnancy\n- Ectopic pregnancy\n- Miscarriage\n- Birth defects (slightly increased risk)\n- Stress and emotional burden\n- Complications from egg retrieval procedure (bleeding, infection)\n- Potential long-term risks (ongoing research)`,
    summary: `IVF in India is a safe, secure, and increasingly popular option offering high success rates at affordable costs. Clinics are equipped with advanced technology, staffed by internationally experienced specialists, and provide comprehensive support services for international patients, including visa and travel assistance.`,
    shortDescription: "Assisted reproductive technology to achieve pregnancy",
    image:ivf,
    duration: "Approximately 2-3 weeks per cycle",
    price: "Affordable treatment for international patients",
    featured: true,
    benefits: [
      "Treatment for a wide range of infertility causes",
      "Option for genetic screening of embryos (PGT)",
      "Fertility preservation for cancer patients",
      "High success rates in accredited Indian clinics"
    ],
    procedures: [
      "Ovarian reserve testing and semen analysis",
      "Ovarian stimulation with hormone injections",
      "Monitoring via ultrasound and blood tests",
      "Egg retrieval procedure",
      "Fertilization in the lab (IVF or ICSI)",
      "Embryo culture and development",
      "Embryo transfer",
      "Pregnancy test and early pregnancy support"
    ]
  },
  {
    id: "8",
    slug: "neurology",
    title: "Neurology",
    category: "Neurology",
    description: `# Neurology`,
    overview: `Neurology is a branch of medicine that diagnoses and treats disorders of the nervous system. Main parts of the nervous system include the brain, spinal cord, and peripheral nerves. These parts control movement and thought. Neurological treatment in India is very affordable and has immense facilities. Neurological disorder treats the conditions that affect the brain, spinal cord, and nervous system. Some of the common reasons to get affected include high blood pressure, air pollution, high fasting plasma glucose, high body mass index and poor diet. Not only these, sometimes other reasons can also affect the brain system such as infection, congenital anomalies, genetic issues, traumatic injuries or environmental factors.`,
    types: `- **Clinical neurology:** Diagnosis and medical management of neurological conditions.\n- **Neurophysiology:** EEG, EMG, nerve conduction studies.\n- **Stroke neurology:** Acute management and prevention of stroke.\n- **Movement disorders:** Management of Parkinson's, tremors, dystonia.\n- **Headache and pain neurology.**\n- **Neuroimmunology:** Management of multiple sclerosis, neuroinflammatory disorders.\n- **Neurorehabilitation.**`,
    purpose: `To diagnose, treat, and manage disorders of the brain, spinal cord, nerves, and muscles, aiming to alleviate symptoms, slow disease progression, improve function, and enhance quality of life.`,
    diseasesTreated: `- Alzheimer's disease and other dementias\n- Parkinson's disease and other movement disorders\n- Stroke (ischemic and hemorrhagic)\n- Epilepsy and seizure disorders\n- Multiple sclerosis\n- Migraine and other headache disorders\n- Neuropathies (e.g., diabetic neuropathy)\n- Myasthenia gravis\n- Guillain-Barré syndrome\n- Bell's Palsy\n- Brain and spinal cord tumors\n- Infections (meningitis, encephalitis)\n- Traumatic brain and spinal cord injuries`,
    risks: `Varies by condition and treatment; diagnostic procedures like lumbar puncture carry risks of headache, bleeding, or infection; medications have side effects.`,
    summary: `Neurology in India provides affordable, high-quality care with access to advanced diagnostic tools (CT, MRI, neurophysiology) and treatments. The concept of neuroplasticity is harnessed in recovery programs. Hospitals are accredited and offer comprehensive international patient services.`,
    shortDescription: "Diagnosis and treatment of nervous system disorders",
    image:Neurology,
    duration: "Varies from chronic management to acute intervention",
    price: "Affordable treatment with comprehensive services",
    featured: false,
    benefits: [
      "Expert management of complex brain and nerve disorders",
      "Advanced diagnostic neuroimaging and testing",
      "Integrated neurorehabilitation programs",
      "Focus on neuroplasticity for recovery"
    ],
    procedures: [
      "Detailed neurological history and examination",
      "Diagnostic testing (CT, MRI, EEG, EMG/NCS, Lumbar Puncture)",
      "Medical management with specific neurology medications",
      "Acute intervention (e.g., thrombolysis for stroke)",
      "Botulinum toxin injections for movement disorders/spasticity",
      "Referral for neurosurgery if needed",
      "Neurorehabilitation therapy"
    ]
  },
  {
    id: "9",
    slug: "oncology",
    title: "Oncology",
    category: "Oncology",
    description: `# Oncology`,
    overview: `Oncology is a medical condition that treats cancer diseases. The treatment of oncology considers diagnosing, treating and preventing cancer. Cancer develops when abnormal cells reproduce and spread throughout the body. The abnormal cells became uncontrollable and spread in other parts that made the disease to be treated at earliest. As science has achieved immense success in the medical field, now the cancers are curable and can be treated. The healthcare professionals who treat cancer are known as Oncologists. Sometimes the treatment needs a team that includes surgeons, radiologists, pathologists, nurses, and other social activists. All the team of highly professionals are committed to care.`,
    types: `- **Medical Oncology:** Treatment with chemotherapy, immunotherapy, targeted therapy, hormone therapy.\n- **Surgical Oncology:** Surgical removal of tumors and cancerous tissue.\n- **Radiation Oncology:** Treatment with radiation therapy.\n- **Gynecologic Oncology:** Cancers of the female reproductive system.\n- **Pediatric Hematology-Oncology:** Cancers in children.\n- **Hematologic Oncology:** Blood cancers (leukemia, lymphoma, myeloma).`,
    purpose: `To diagnose cancer accurately, provide curative or life-prolonging treatment, manage symptoms, prevent recurrence, and offer palliative care to improve quality of life.`,
    diseasesTreated: `- Carcinomas (e.g., lung, breast, colorectal, prostate, skin cancers)\n- Sarcomas (bone, soft tissue)\n- Leukemias (blood and bone marrow cancers)\n- Lymphomas (Hodgkin's and Non-Hodgkin's)\n- Central nervous system cancers (brain and spinal cord tumors)\n- Gynecological cancers (cervical, ovarian, uterine)\n- Gastrointestinal cancers (stomach, pancreatic, liver)\n- Head and neck cancers\n- Genitourinary cancers (bladder, kidney, testicular)`,
    risks: `Treatment risks vary:\n- **Surgery:** Bleeding, infection, organ damage.\n- **Chemotherapy:** Nausea, fatigue, hair loss, low blood counts, increased infection risk, organ toxicity.\n- **Radiation:** Skin irritation, fatigue, damage to nearby tissues, secondary cancers.\n- **Immunotherapy/Targeted therapy:** Unique side effects like autoimmune reactions.`,
    summary: `Oncology in India offers a wide range of treatments using advanced technology, including robotic surgery, precision radiation, and novel systemic therapies. Care is delivered by multidisciplinary teams in accredited hospitals. India is a preferred destination for international patients due to high-quality, affordable care and comprehensive support services.`,
    shortDescription: "Comprehensive diagnosis, treatment, and care for cancer",
    image: Oncology,
    duration: "Varies from short-term to long-term/lifelong management",
    price: "High-quality treatment at most affordable cost",
    featured: true,
    benefits: [
      "Multidisciplinary team approach for personalized care",
      "Access to latest treatments (immunotherapy, targeted therapy)",
      "Advanced surgical techniques including robotic surgery",
      "Precision radiation therapy and palliative care support"
    ],
    procedures: [
<<<<<<< HEAD
      'Pre-operative preparation',
      'Small incision creation',
      'Camera and instrument insertion',
      'Surgical procedure performance',
      'Closure and recovery',
      'Same-day or next-day discharge',
    ],
  },
  {
    id: '6',
    title: 'Coronary Artery Bypass',
    category: 'Cardiac Surgery',
    description: 'Life-saving open-heart surgery to improve blood flow to the heart muscle. Our cardiac surgeons perform both traditional and minimally invasive bypass procedures, creating new routes around blocked arteries using healthy blood vessels from other parts of the body. Comprehensive cardiac rehabilitation ensures optimal recovery.',
    shortDescription: 'Heart bypass surgery for blocked arteries',
    image: '/doctor-img2 1.png',
    duration: '3-6 hours',
    price: '$70,000 - $150,000',
    featured: false,
    benefits: [
      'Improved heart blood flow',
      'Relief from chest pain',
      'Reduced heart attack risk',
      'Extended life expectancy',
      'Enhanced quality of life',
    ],
    procedures: [
      'Comprehensive cardiac evaluation',
      'Surgical planning and preparation',
      'Chest opening and heart access',
      'Bypass graft creation',
      'Heart-lung machine management',
      'Intensive post-operative care',
    ],
  },
  {
    id: '7',
    title: 'Spinal Fusion Surgery',
    category: 'Orthopedic Surgery',
    description: 'Surgical procedure to permanently connect two or more vertebrae in the spine, eliminating motion between them. Using advanced techniques including minimally invasive approaches, our spine surgeons treat conditions like degenerative disc disease, spinal stenosis, and scoliosis, providing lasting pain relief and stability.',
    shortDescription: 'Spine stabilization and pain relief surgery',
    image: '/doctor.png',
    duration: '3-5 hours',
    price: '$30,000 - $80,000',
    featured: false,
    benefits: [
      'Chronic pain relief',
      'Spinal stability restoration',
      'Nerve pressure reduction',
      'Improved posture and function',
      'Long-term solution',
    ],
    procedures: [
      'Detailed spinal imaging',
      'Surgical approach planning',
      'Bone graft preparation',
      'Vertebrae fusion',
      'Hardware implantation',
      'Rehabilitation program',
    ],
  },
  {
    id: '8',
    title: 'Stroke Treatment',
    category: 'Neurology Treatment',
    description: 'Emergency and comprehensive stroke care including clot-busting medications, mechanical thrombectomy, and neurorehabilitation. Our stroke team provides rapid response 24/7, using advanced imaging and treatment protocols to minimize brain damage and maximize recovery potential. Time-critical intervention saves lives and function.',
    shortDescription: 'Emergency stroke intervention and care',
    image: '/doctor-img 1.png',
    duration: '1-6 hours',
    price: '$20,000 - $60,000',
    featured: true,
    benefits: [
      'Rapid intervention saves brain tissue',
      'Minimizes long-term disability',
      '24/7 stroke team availability',
      'Advanced clot removal technology',
      'Comprehensive rehabilitation',
    ],
    procedures: [
      'Immediate assessment and imaging',
      'Rapid treatment decision',
      'Clot-busting medication or surgery',
      'Intensive monitoring',
      'Neurological assessment',
      'Rehabilitation planning',
    ],
  },
  {
    id: '9',
    title: 'Prostate Treatment',
    category: 'Urology Surgery',
    description: 'Comprehensive treatment options for enlarged prostate and prostate cancer including minimally invasive procedures, robotic surgery, and radiation therapy. Our urologists provide personalized care plans using the latest technology to treat prostate conditions while preserving quality of life and function.',
    shortDescription: 'Advanced prostate care and treatment',
    image: '/doctor-img2 1.png',
    duration: '2-4 hours',
    price: '$10,000 - $40,000',
    featured: false,
    benefits: [
      'Symptom relief',
      'Function preservation',
      'Multiple treatment options',
      'Minimally invasive approaches',
      'Personalized care plans',
    ],
    procedures: [
      'Comprehensive prostate evaluation',
      'Treatment option consultation',
      'Procedure performance',
      'Post-treatment monitoring',
      'Follow-up care',
      'Quality of life assessment',
    ],
  },
  {
    id: '10',
    title: 'Hernia Repair',
    category: 'General Surgery',
    description: 'Expert surgical repair of inguinal, umbilical, hiatal, and ventral hernias using both open and laparoscopic techniques. Our surgeons use the latest mesh materials and tension-free repair methods to ensure strong, lasting results with minimal recurrence risk and faster return to normal activities.',
    shortDescription: 'Surgical hernia correction and repair',
    image: '/doctor.png',
    duration: '1-2 hours',
    price: '$5,000 - $15,000',
    featured: false,
    benefits: [
      'Pain and discomfort relief',
      'Prevention of complications',
      'Quick recovery time',
      'Low recurrence rate',
      'Minimal scarring',
    ],
    procedures: [
      'Physical examination',
      'Surgical approach selection',
      'Hernia reduction',
      'Mesh placement if needed',
      'Tissue reinforcement',
      'Same-day discharge often possible',
    ],
  },
  {
    id: '11',
    title: 'Chemotherapy Treatment',
    category: 'Cancer Treatment',
    description: 'Comprehensive cancer treatment using latest chemotherapy protocols and targeted therapies. Our oncology team provides personalized treatment plans with advanced supportive care to minimize side effects and maximize effectiveness.',
    shortDescription: 'Advanced cancer treatment with chemotherapy',
    image: '/doctor-img 1.png',
    duration: 'Multiple sessions',
    price: '$20,000 - $80,000',
    featured: true,
    benefits: [
      'Targeted cancer cell destruction',
      'Personalized treatment protocols',
      'Advanced supportive care',
      'Regular monitoring and adjustment',
      'Multidisciplinary approach',
    ],
    procedures: [
      'Comprehensive cancer evaluation',
      'Treatment plan development',
      'Chemotherapy administration',
      'Side effect management',
      'Regular monitoring',
      'Follow-up care',
    ],
  },
  {
    id: '12',
    title: 'Rhinoplasty Surgery',
    category: 'Cosmetic Surgery',
    description: 'Aesthetic and functional nose surgery performed by expert cosmetic surgeons. We specialize in both cosmetic enhancement and functional correction to improve breathing and appearance.',
    shortDescription: 'Cosmetic nose reshaping surgery',
    image: '/doctor-img2 1.png',
    duration: '2-3 hours',
    price: '$8,000 - $20,000',
    featured: false,
    benefits: [
      'Improved facial harmony',
      'Enhanced self-confidence',
      'Better breathing function',
      'Natural-looking results',
      'Minimal scarring',
    ],
    procedures: [
      'Consultation and planning',
      'Anesthesia administration',
      'Surgical reshaping',
      'Functional corrections',
      'Recovery and healing',
      'Follow-up assessments',
    ],
  },
  {
    id: '13',
    title: 'Dental Implants',
    category: 'Dental Treatment',
    description: 'Permanent tooth replacement using titanium implants and custom crowns. Our dental specialists provide complete implant solutions from extraction to final restoration.',
    shortDescription: 'Permanent dental implant solutions',
    image: '/doctor.png',
    duration: '1-2 hours per implant',
    price: '$2,500 - $6,000 per tooth',
    featured: false,
    benefits: [
      'Permanent tooth replacement',
      'Natural appearance and function',
      'Preserves jawbone health',
      'Long-lasting solution',
      'Improved quality of life',
    ],
    procedures: [
      'Dental examination and planning',
      'Implant placement surgery',
      'Healing period (3-6 months)',
      'Abutment placement',
      'Crown fabrication and placement',
      'Follow-up care',
    ],
  },
  {
    id: '14',
    title: 'Sinus Surgery',
    category: 'Ear Nose Throat Surgery',
    description: 'Endoscopic sinus surgery to treat chronic sinusitis and nasal polyps. Our ENT specialists use minimally invasive techniques for optimal outcomes.',
    shortDescription: 'Minimally invasive sinus treatment',
    image: '/doctor-img 1.png',
    duration: '1-2 hours',
    price: '$8,000 - $15,000',
    featured: false,
    benefits: [
      'Relief from chronic sinus issues',
      'Improved breathing',
      'Minimally invasive approach',
      'Quick recovery time',
      'Long-lasting results',
    ],
    procedures: [
      'Endoscopic examination',
      'Anesthesia administration',
      'Endoscopic sinus surgery',
      'Polyp removal if needed',
      'Post-operative care',
      'Follow-up monitoring',
    ],
  },
  {
    id: '15',
    title: 'LASIK Eye Surgery',
    category: 'Eye Treatment',
    description: 'Advanced laser vision correction for nearsightedness, farsightedness, and astigmatism. Our ophthalmologists use state-of-the-art LASIK technology for precise corneal reshaping.',
    shortDescription: 'Laser vision correction surgery',
    image: '/doctor-img2 1.png',
    duration: '15-30 minutes',
    price: '$3,000 - $6,000 per eye',
    featured: true,
    benefits: [
      'Clear vision without glasses',
      'Quick procedure and recovery',
      'High success rate',
      'Minimal discomfort',
      'Long-lasting results',
    ],
    procedures: [
      'Comprehensive eye examination',
      'Corneal mapping and measurements',
      'Laser corneal reshaping',
      'Post-operative eye drops',
      'Follow-up evaluations',
      'Vision monitoring',
    ],
  },
  {
    id: '16',
    title: 'Colonoscopy Procedure',
    category: 'Gastroenterology Surgery',
    description: 'Diagnostic and therapeutic colonoscopy for colon health screening and treatment. Our gastroenterologists provide comprehensive GI care with advanced endoscopic technology.',
    shortDescription: 'Colon screening and treatment',
    image: '/doctor.png',
    duration: '30-60 minutes',
    price: '$2,000 - $5,000',
    featured: false,
    benefits: [
      'Early cancer detection',
      'Polyp removal during procedure',
      'Diagnostic accuracy',
      'Preventive care',
      'Minimal discomfort',
    ],
    procedures: [
      'Bowel preparation',
      'Sedation administration',
      'Endoscopic examination',
      'Biopsy or polyp removal if needed',
      'Recovery monitoring',
      'Results discussion',
    ],
  },
  {
    id: '17',
    title: 'Hysterectomy Surgery',
    category: 'Gynaecology Treatment',
    description: 'Minimally invasive hysterectomy procedures including laparoscopic and robotic approaches. Our gynecologists provide comprehensive care for various gynecological conditions.',
    shortDescription: 'Advanced gynecological surgery',
    image: '/doctor-img 1.png',
    duration: '2-4 hours',
    price: '$12,000 - $25,000',
    featured: false,
    benefits: [
      'Relief from symptoms',
      'Minimally invasive options',
      'Faster recovery',
      'Expert surgical care',
      'Comprehensive support',
    ],
    procedures: [
      'Pre-operative evaluation',
      'Surgical approach selection',
      'Hysterectomy procedure',
      'Post-operative monitoring',
      'Pain management',
      'Follow-up care',
    ],
  },
  {
    id: '18',
    title: 'Dialysis Treatment',
    category: 'Nephrology Treatment',
    description: 'Advanced hemodialysis and peritoneal dialysis for kidney failure management. Our nephrology team provides comprehensive renal care with state-of-the-art dialysis equipment.',
    shortDescription: 'Kidney dialysis treatment',
    image: '/doctor-img2 1.png',
    duration: '3-4 hours per session',
    price: '$500 - $1,500 per session',
    featured: false,
    benefits: [
      'Blood toxin removal',
      'Fluid balance management',
      'Quality of life improvement',
      'Expert monitoring',
      'Comprehensive renal care',
    ],
    procedures: [
      'Vascular access creation',
      'Dialysis initiation',
      'Regular treatment sessions',
      'Vital signs monitoring',
      'Lab work evaluation',
      'Ongoing management',
    ],
  },
  {
    id: '19',
    title: 'Liver Transplant',
    category: 'Organ Transplant Surgery',
    description: 'Complex liver transplant surgery performed by expert transplant surgeons. We provide complete pre-transplant evaluation, surgery, and post-transplant care.',
    shortDescription: 'Life-saving liver transplant surgery',
    image: '/doctor.png',
    duration: '8-12 hours',
    price: '$150,000 - $300,000',
    featured: true,
    benefits: [
      'Life-saving procedure',
      'Expert transplant team',
      'Comprehensive care',
      'Post-transplant support',
      'Quality of life improvement',
    ],
    procedures: [
      'Transplant evaluation',
      'Donor matching',
      'Liver transplant surgery',
      'Intensive care monitoring',
      'Immunosuppression management',
      'Long-term follow-up',
    ],
  },
  {
    id: '20',
    title: 'Robotic Prostatectomy',
    category: 'Robotic Surgery',
    description: 'Da Vinci robotic surgery for prostate cancer with enhanced precision and minimal invasiveness. Our robotic surgeons use the latest technology for optimal outcomes.',
    shortDescription: 'Robotic-assisted prostate surgery',
    image: '/doctor-img 1.png',
    duration: '3-4 hours',
    price: '$25,000 - $45,000',
    featured: true,
    benefits: [
      'Enhanced surgical precision',
      'Minimal blood loss',
      'Faster recovery',
      'Better functional outcomes',
      'Smaller incisions',
    ],
    procedures: [
      'Pre-operative assessment',
      'Robotic system setup',
      'Precise prostate removal',
      'Lymph node evaluation',
      'Post-operative care',
      'Functional recovery support',
    ],
  },
  {
    id: '21',
    title: 'Stem Cell Treatment',
    category: 'Stem Cell Therapy',
    description: 'Regenerative medicine using stem cells for various conditions including orthopedic injuries, autoimmune disorders, and degenerative diseases.',
    shortDescription: 'Advanced regenerative stem cell therapy',
    image: '/doctor-img2 1.png',
    duration: '2-4 hours',
    price: '$15,000 - $50,000',
    featured: false,
    benefits: [
      'Tissue regeneration',
      'Natural healing promotion',
      'Minimally invasive',
      'Reduced inflammation',
      'Long-term improvement',
    ],
    procedures: [
      'Patient evaluation',
      'Stem cell harvesting',
      'Cell processing and preparation',
      'Stem cell injection',
      'Monitoring and assessment',
      'Follow-up treatments',
    ],
  },
  {
    id: '22',
    title: 'Bariatric Surgery',
    category: 'Weight Loss Treatment',
    description: 'Weight loss surgery including gastric bypass, sleeve gastrectomy, and gastric banding. Our bariatric team provides comprehensive weight management solutions.',
    shortDescription: 'Surgical weight loss procedures',
    image: '/doctor.png',
    duration: '2-4 hours',
    price: '$18,000 - $35,000',
    featured: true,
    benefits: [
      'Significant weight loss',
      'Health improvement',
      'Metabolic benefits',
      'Sustained results',
      'Lifestyle transformation',
    ],
    procedures: [
      'Comprehensive evaluation',
      'Pre-operative preparation',
      'Bariatric surgery',
      'Post-operative monitoring',
      'Nutritional counseling',
      'Long-term follow-up',
    ],
  },
];
