import { Treatment } from './types';

export const treatmentsData: Treatment[] = [
  {
    id: '1',
    title: 'Cardiac Catheterization',
    category: 'Cardiac Surgery',
    description: 'A minimally invasive procedure to diagnose and treat cardiovascular conditions. Our state-of-the-art cardiac catheterization lab uses advanced imaging technology to guide thin, flexible tubes through blood vessels to the heart. This procedure helps identify blockages, measure pressure, and assess heart function with precision and safety.',
    shortDescription: 'Minimally invasive heart diagnostic and treatment procedure',
    image: '/doctor.png',
    duration: '1-2 hours',
    price: '$3,500 - $8,000',
    featured: true,
    benefits: [
      'Accurate diagnosis of heart conditions',
      'Minimally invasive with faster recovery',
      'Real-time imaging and assessment',
      'Can treat blockages during same procedure',
      'Lower risk compared to open surgery',
    ],
    procedures: [
      'Patient preparation and local anesthesia',
      'Catheter insertion through blood vessel',
      'Navigation to heart using X-ray guidance',
      'Diagnostic imaging and measurements',
      'Treatment if necessary (angioplasty/stent)',
      'Recovery and monitoring',
    ],
  },
  {
    id: '2',
    title: 'Joint Replacement Surgery',
    category: 'Orthopedic Surgery',
    description: 'Advanced joint replacement procedures using cutting-edge prosthetic technology and minimally invasive surgical techniques. Our orthopedic surgeons specialize in hip, knee, and shoulder replacements, providing customized solutions to restore mobility and eliminate chronic pain. We use the latest materials and computer-assisted surgery for optimal outcomes.',
    shortDescription: 'Restore mobility with advanced joint replacement',
    image: '/doctor-img 1.png',
    duration: '2-3 hours',
    price: '$15,000 - $35,000',
    featured: true,
    benefits: [
      'Pain relief and improved mobility',
      'Long-lasting prosthetic joints',
      'Customized implant fitting',
      'Minimally invasive techniques',
      'Comprehensive rehabilitation program',
    ],
    procedures: [
      'Pre-operative assessment and planning',
      'Surgical removal of damaged joint',
      'Precise implant positioning',
      'Computer-assisted alignment',
      'Post-operative care and monitoring',
      'Physical therapy and rehabilitation',
    ],
  },
  {
    id: '3',
    title: 'Brain Tumor Surgery',
    category: 'Brain and Spine Surgery',
    description: 'Expert neurosurgical treatment for brain tumors using advanced techniques including microsurgery, neuronavigation, and intraoperative monitoring. Our neurosurgery team combines precision technology with extensive experience to safely remove tumors while preserving critical brain functions. We offer comprehensive care from diagnosis through recovery.',
    shortDescription: 'Advanced neurosurgical brain tumor treatment',
    image: '/doctor-img2 1.png',
    duration: '4-8 hours',
    price: '$50,000 - $100,000',
    featured: true,
    benefits: [
      'Precision tumor removal',
      'Brain function preservation',
      'Advanced imaging guidance',
      'Minimized surgical trauma',
      'Multidisciplinary care team',
    ],
    procedures: [
      'Comprehensive neurological evaluation',
      'Advanced imaging and mapping',
      'Craniotomy and tumor access',
      'Microsurgical tumor removal',
      'Intraoperative monitoring',
      'Intensive care and recovery',
    ],
  },
  {
    id: '4',
    title: 'Kidney Stone Removal',
    category: 'Urology Surgery',
    description: 'Modern minimally invasive treatments for kidney stones including laser lithotripsy, ureteroscopy, and extracorporeal shock wave lithotripsy (ESWL). Our urologists use the latest technology to safely and effectively remove stones of all sizes, providing rapid pain relief and preventing future complications.',
    shortDescription: 'Minimally invasive kidney stone treatment',
    image: '/doctor.png',
    duration: '1-3 hours',
    price: '$5,000 - $12,000',
    featured: false,
    benefits: [
      'Quick pain relief',
      'Minimally invasive procedures',
      'No major incisions required',
      'Fast recovery time',
      'Prevention guidance included',
    ],
    procedures: [
      'Diagnostic imaging and stone analysis',
      'Procedure selection based on stone size',
      'Minimally invasive stone fragmentation',
      'Stone removal or passage',
      'Post-procedure monitoring',
      'Follow-up care and prevention plan',
    ],
  },
  {
    id: '5',
    title: 'Laparoscopic Surgery',
    category: 'General Surgery',
    description: 'Minimally invasive surgical procedures performed through small incisions using specialized instruments and camera systems. Our general surgeons are experts in laparoscopic techniques for gallbladder removal, hernia repair, appendectomy, and other abdominal procedures, resulting in less pain, smaller scars, and faster recovery.',
    shortDescription: 'Minimally invasive surgical procedures',
    image: '/doctor-img 1.png',
    duration: '1-4 hours',
    price: '$8,000 - $20,000',
    featured: true,
    benefits: [
      'Smaller incisions and scars',
      'Reduced post-operative pain',
      'Faster recovery time',
      'Lower infection risk',
      'Shorter hospital stay',
    ],
    procedures: [
      'Pre-operative preparation',
      'Small incision creation',
      'Camera and instrument insertion',
      'Surgical procedure performance',
      'Closure and recovery',
      'Same-day or next-day discharge',
    ],
  },
  {
    id: '6',
    title: 'Coronary Artery Bypass',
    category: 'Cardiac Surgery',
    description: 'Life-saving open-heart surgery to improve blood flow to the heart muscle. Our cardiac surgeons perform both traditional and minimally invasive bypass procedures, creating new routes around blocked arteries using healthy blood vessels from other parts of the body. Comprehensive cardiac rehabilitation ensures optimal recovery.',
    shortDescription: 'Heart bypass surgery for blocked arteries',
    image: '/doctor-img2 1.png',
    duration: '3-6 hours',
    price: '$70,000 - $150,000',
    featured: false,
    benefits: [
      'Improved heart blood flow',
      'Relief from chest pain',
      'Reduced heart attack risk',
      'Extended life expectancy',
      'Enhanced quality of life',
    ],
    procedures: [
      'Comprehensive cardiac evaluation',
      'Surgical planning and preparation',
      'Chest opening and heart access',
      'Bypass graft creation',
      'Heart-lung machine management',
      'Intensive post-operative care',
    ],
  },
  {
    id: '7',
    title: 'Spinal Fusion Surgery',
    category: 'Orthopedic Surgery',
    description: 'Surgical procedure to permanently connect two or more vertebrae in the spine, eliminating motion between them. Using advanced techniques including minimally invasive approaches, our spine surgeons treat conditions like degenerative disc disease, spinal stenosis, and scoliosis, providing lasting pain relief and stability.',
    shortDescription: 'Spine stabilization and pain relief surgery',
    image: '/doctor.png',
    duration: '3-5 hours',
    price: '$30,000 - $80,000',
    featured: false,
    benefits: [
      'Chronic pain relief',
      'Spinal stability restoration',
      'Nerve pressure reduction',
      'Improved posture and function',
      'Long-term solution',
    ],
    procedures: [
      'Detailed spinal imaging',
      'Surgical approach planning',
      'Bone graft preparation',
      'Vertebrae fusion',
      'Hardware implantation',
      'Rehabilitation program',
    ],
  },
  {
    id: '8',
    title: 'Stroke Treatment',
    category: 'Neurology Treatment',
    description: 'Emergency and comprehensive stroke care including clot-busting medications, mechanical thrombectomy, and neurorehabilitation. Our stroke team provides rapid response 24/7, using advanced imaging and treatment protocols to minimize brain damage and maximize recovery potential. Time-critical intervention saves lives and function.',
    shortDescription: 'Emergency stroke intervention and care',
    image: '/doctor-img 1.png',
    duration: '1-6 hours',
    price: '$20,000 - $60,000',
    featured: true,
    benefits: [
      'Rapid intervention saves brain tissue',
      'Minimizes long-term disability',
      '24/7 stroke team availability',
      'Advanced clot removal technology',
      'Comprehensive rehabilitation',
    ],
    procedures: [
      'Immediate assessment and imaging',
      'Rapid treatment decision',
      'Clot-busting medication or surgery',
      'Intensive monitoring',
      'Neurological assessment',
      'Rehabilitation planning',
    ],
  },
  {
    id: '9',
    title: 'Prostate Treatment',
    category: 'Urology Surgery',
    description: 'Comprehensive treatment options for enlarged prostate and prostate cancer including minimally invasive procedures, robotic surgery, and radiation therapy. Our urologists provide personalized care plans using the latest technology to treat prostate conditions while preserving quality of life and function.',
    shortDescription: 'Advanced prostate care and treatment',
    image: '/doctor-img2 1.png',
    duration: '2-4 hours',
    price: '$10,000 - $40,000',
    featured: false,
    benefits: [
      'Symptom relief',
      'Function preservation',
      'Multiple treatment options',
      'Minimally invasive approaches',
      'Personalized care plans',
    ],
    procedures: [
      'Comprehensive prostate evaluation',
      'Treatment option consultation',
      'Procedure performance',
      'Post-treatment monitoring',
      'Follow-up care',
      'Quality of life assessment',
    ],
  },
  {
    id: '10',
    title: 'Hernia Repair',
    category: 'General Surgery',
    description: 'Expert surgical repair of inguinal, umbilical, hiatal, and ventral hernias using both open and laparoscopic techniques. Our surgeons use the latest mesh materials and tension-free repair methods to ensure strong, lasting results with minimal recurrence risk and faster return to normal activities.',
    shortDescription: 'Surgical hernia correction and repair',
    image: '/doctor.png',
    duration: '1-2 hours',
    price: '$5,000 - $15,000',
    featured: false,
    benefits: [
      'Pain and discomfort relief',
      'Prevention of complications',
      'Quick recovery time',
      'Low recurrence rate',
      'Minimal scarring',
    ],
    procedures: [
      'Physical examination',
      'Surgical approach selection',
      'Hernia reduction',
      'Mesh placement if needed',
      'Tissue reinforcement',
      'Same-day discharge often possible',
    ],
  },
  {
    id: '11',
    title: 'Chemotherapy Treatment',
    category: 'Cancer Treatment',
    description: 'Comprehensive cancer treatment using latest chemotherapy protocols and targeted therapies. Our oncology team provides personalized treatment plans with advanced supportive care to minimize side effects and maximize effectiveness.',
    shortDescription: 'Advanced cancer treatment with chemotherapy',
    image: '/doctor-img 1.png',
    duration: 'Multiple sessions',
    price: '$20,000 - $80,000',
    featured: true,
    benefits: [
      'Targeted cancer cell destruction',
      'Personalized treatment protocols',
      'Advanced supportive care',
      'Regular monitoring and adjustment',
      'Multidisciplinary approach',
    ],
    procedures: [
      'Comprehensive cancer evaluation',
      'Treatment plan development',
      'Chemotherapy administration',
      'Side effect management',
      'Regular monitoring',
      'Follow-up care',
    ],
  },
  {
    id: '12',
    title: 'Rhinoplasty Surgery',
    category: 'Cosmetic Surgery',
    description: 'Aesthetic and functional nose surgery performed by expert cosmetic surgeons. We specialize in both cosmetic enhancement and functional correction to improve breathing and appearance.',
    shortDescription: 'Cosmetic nose reshaping surgery',
    image: '/doctor-img2 1.png',
    duration: '2-3 hours',
    price: '$8,000 - $20,000',
    featured: false,
    benefits: [
      'Improved facial harmony',
      'Enhanced self-confidence',
      'Better breathing function',
      'Natural-looking results',
      'Minimal scarring',
    ],
    procedures: [
      'Consultation and planning',
      'Anesthesia administration',
      'Surgical reshaping',
      'Functional corrections',
      'Recovery and healing',
      'Follow-up assessments',
    ],
  },
  {
    id: '13',
    title: 'Dental Implants',
    category: 'Dental Treatment',
    description: 'Permanent tooth replacement using titanium implants and custom crowns. Our dental specialists provide complete implant solutions from extraction to final restoration.',
    shortDescription: 'Permanent dental implant solutions',
    image: '/doctor.png',
    duration: '1-2 hours per implant',
    price: '$2,500 - $6,000 per tooth',
    featured: false,
    benefits: [
      'Permanent tooth replacement',
      'Natural appearance and function',
      'Preserves jawbone health',
      'Long-lasting solution',
      'Improved quality of life',
    ],
    procedures: [
      'Dental examination and planning',
      'Implant placement surgery',
      'Healing period (3-6 months)',
      'Abutment placement',
      'Crown fabrication and placement',
      'Follow-up care',
    ],
  },
  {
    id: '14',
    title: 'Sinus Surgery',
    category: 'Ear Nose Throat Surgery',
    description: 'Endoscopic sinus surgery to treat chronic sinusitis and nasal polyps. Our ENT specialists use minimally invasive techniques for optimal outcomes.',
    shortDescription: 'Minimally invasive sinus treatment',
    image: '/doctor-img 1.png',
    duration: '1-2 hours',
    price: '$8,000 - $15,000',
    featured: false,
    benefits: [
      'Relief from chronic sinus issues',
      'Improved breathing',
      'Minimally invasive approach',
      'Quick recovery time',
      'Long-lasting results',
    ],
    procedures: [
      'Endoscopic examination',
      'Anesthesia administration',
      'Endoscopic sinus surgery',
      'Polyp removal if needed',
      'Post-operative care',
      'Follow-up monitoring',
    ],
  },
  {
    id: '15',
    title: 'LASIK Eye Surgery',
    category: 'Eye Treatment',
    description: 'Advanced laser vision correction for nearsightedness, farsightedness, and astigmatism. Our ophthalmologists use state-of-the-art LASIK technology for precise corneal reshaping.',
    shortDescription: 'Laser vision correction surgery',
    image: '/doctor-img2 1.png',
    duration: '15-30 minutes',
    price: '$3,000 - $6,000 per eye',
    featured: true,
    benefits: [
      'Clear vision without glasses',
      'Quick procedure and recovery',
      'High success rate',
      'Minimal discomfort',
      'Long-lasting results',
    ],
    procedures: [
      'Comprehensive eye examination',
      'Corneal mapping and measurements',
      'Laser corneal reshaping',
      'Post-operative eye drops',
      'Follow-up evaluations',
      'Vision monitoring',
    ],
  },
  {
    id: '16',
    title: 'Colonoscopy Procedure',
    category: 'Gastroenterology Surgery',
    description: 'Diagnostic and therapeutic colonoscopy for colon health screening and treatment. Our gastroenterologists provide comprehensive GI care with advanced endoscopic technology.',
    shortDescription: 'Colon screening and treatment',
    image: '/doctor.png',
    duration: '30-60 minutes',
    price: '$2,000 - $5,000',
    featured: false,
    benefits: [
      'Early cancer detection',
      'Polyp removal during procedure',
      'Diagnostic accuracy',
      'Preventive care',
      'Minimal discomfort',
    ],
    procedures: [
      'Bowel preparation',
      'Sedation administration',
      'Endoscopic examination',
      'Biopsy or polyp removal if needed',
      'Recovery monitoring',
      'Results discussion',
    ],
  },
  {
    id: '17',
    title: 'Hysterectomy Surgery',
    category: 'Gynaecology Treatment',
    description: 'Minimally invasive hysterectomy procedures including laparoscopic and robotic approaches. Our gynecologists provide comprehensive care for various gynecological conditions.',
    shortDescription: 'Advanced gynecological surgery',
    image: '/doctor-img 1.png',
    duration: '2-4 hours',
    price: '$12,000 - $25,000',
    featured: false,
    benefits: [
      'Relief from symptoms',
      'Minimally invasive options',
      'Faster recovery',
      'Expert surgical care',
      'Comprehensive support',
    ],
    procedures: [
      'Pre-operative evaluation',
      'Surgical approach selection',
      'Hysterectomy procedure',
      'Post-operative monitoring',
      'Pain management',
      'Follow-up care',
    ],
  },
  {
    id: '18',
    title: 'Dialysis Treatment',
    category: 'Nephrology Treatment',
    description: 'Advanced hemodialysis and peritoneal dialysis for kidney failure management. Our nephrology team provides comprehensive renal care with state-of-the-art dialysis equipment.',
    shortDescription: 'Kidney dialysis treatment',
    image: '/doctor-img2 1.png',
    duration: '3-4 hours per session',
    price: '$500 - $1,500 per session',
    featured: false,
    benefits: [
      'Blood toxin removal',
      'Fluid balance management',
      'Quality of life improvement',
      'Expert monitoring',
      'Comprehensive renal care',
    ],
    procedures: [
      'Vascular access creation',
      'Dialysis initiation',
      'Regular treatment sessions',
      'Vital signs monitoring',
      'Lab work evaluation',
      'Ongoing management',
    ],
  },
  {
    id: '19',
    title: 'Liver Transplant',
    category: 'Organ Transplant Surgery',
    description: 'Complex liver transplant surgery performed by expert transplant surgeons. We provide complete pre-transplant evaluation, surgery, and post-transplant care.',
    shortDescription: 'Life-saving liver transplant surgery',
    image: '/doctor.png',
    duration: '8-12 hours',
    price: '$150,000 - $300,000',
    featured: true,
    benefits: [
      'Life-saving procedure',
      'Expert transplant team',
      'Comprehensive care',
      'Post-transplant support',
      'Quality of life improvement',
    ],
    procedures: [
      'Transplant evaluation',
      'Donor matching',
      'Liver transplant surgery',
      'Intensive care monitoring',
      'Immunosuppression management',
      'Long-term follow-up',
    ],
  },
  {
    id: '20',
    title: 'Robotic Prostatectomy',
    category: 'Robotic Surgery',
    description: 'Da Vinci robotic surgery for prostate cancer with enhanced precision and minimal invasiveness. Our robotic surgeons use the latest technology for optimal outcomes.',
    shortDescription: 'Robotic-assisted prostate surgery',
    image: '/doctor-img 1.png',
    duration: '3-4 hours',
    price: '$25,000 - $45,000',
    featured: true,
    benefits: [
      'Enhanced surgical precision',
      'Minimal blood loss',
      'Faster recovery',
      'Better functional outcomes',
      'Smaller incisions',
    ],
    procedures: [
      'Pre-operative assessment',
      'Robotic system setup',
      'Precise prostate removal',
      'Lymph node evaluation',
      'Post-operative care',
      'Functional recovery support',
    ],
  },
  {
    id: '21',
    title: 'Stem Cell Treatment',
    category: 'Stem Cell Therapy',
    description: 'Regenerative medicine using stem cells for various conditions including orthopedic injuries, autoimmune disorders, and degenerative diseases.',
    shortDescription: 'Advanced regenerative stem cell therapy',
    image: '/doctor-img2 1.png',
    duration: '2-4 hours',
    price: '$15,000 - $50,000',
    featured: false,
    benefits: [
      'Tissue regeneration',
      'Natural healing promotion',
      'Minimally invasive',
      'Reduced inflammation',
      'Long-term improvement',
    ],
    procedures: [
      'Patient evaluation',
      'Stem cell harvesting',
      'Cell processing and preparation',
      'Stem cell injection',
      'Monitoring and assessment',
      'Follow-up treatments',
    ],
  },
  {
    id: '22',
    title: 'Bariatric Surgery',
    category: 'Weight Loss Treatment',
    description: 'Weight loss surgery including gastric bypass, sleeve gastrectomy, and gastric banding. Our bariatric team provides comprehensive weight management solutions.',
    shortDescription: 'Surgical weight loss procedures',
    image: '/doctor.png',
    duration: '2-4 hours',
    price: '$18,000 - $35,000',
    featured: true,
    benefits: [
      'Significant weight loss',
      'Health improvement',
      'Metabolic benefits',
      'Sustained results',
      'Lifestyle transformation',
    ],
    procedures: [
      'Comprehensive evaluation',
      'Pre-operative preparation',
      'Bariatric surgery',
      'Post-operative monitoring',
      'Nutritional counseling',
      'Long-term follow-up',
    ],
  },
];
