import { Testimonial } from './types';

// Comprehensive testimonial data
export const testimonials: Testimonial[] = [
  {
    id: 'test-001',
    name: 'John Smith',
    age: 58,
    country: 'United States',
    countryFlag: '🇺🇸',
    treatment: 'Cardiac Bypass Surgery',
    hospital: 'Manal Heart Institute',
    doctor: 'Dr. Rajesh Kumar',
    rating: 5,
    date: '2025-12-15',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
    testimonial: 'My experience at Manal Healthcare was exceptional. The cardiac surgery team was highly professional, and Dr. Kumar explained every step of the procedure. The post-operative care was outstanding, and I recovered faster than expected. The facility was world-class, and the staff was incredibly caring. I highly recommend Manal Healthcare to anyone seeking quality medical care at affordable prices.',
    verified: true,
    featured: true,
    category: 'Cardiac Care',
  },
  {
    id: 'test-002',
    name: 'Sarah Johnson',
    age: 45,
    country: 'United Kingdom',
    countryFlag: '🇬🇧',
    treatment: 'Knee Replacement Surgery',
    hospital: 'Manal Orthopedic Center',
    doctor: 'Dr. Priya Sharma',
    rating: 5,
    date: '2025-11-28',
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400',
    testimonial: 'After years of knee pain, I decided to have my surgery at Manal Healthcare. The entire process from consultation to post-surgery rehabilitation was smooth and professional. Dr. Sharma is an excellent surgeon, and the physiotherapy team helped me regain mobility quickly. The cost was significantly lower than in the UK, and the quality was even better.',
    verified: true,
    featured: true,
    category: 'Orthopedic',
  },
  {
    id: 'test-003',
    name: 'Mohammed Al-Faisal',
    age: 42,
    country: 'Saudi Arabia',
    countryFlag: '🇸🇦',
    treatment: 'Cosmetic Rhinoplasty',
    hospital: 'Manal Cosmetic Surgery Center',
    doctor: 'Dr. Anjali Mehta',
    rating: 5,
    date: '2025-11-10',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400',
    testimonial: 'I traveled from Saudi Arabia for cosmetic surgery, and it was the best decision. Dr. Mehta is highly skilled and understood exactly what I wanted. The results are natural and exceed my expectations. The hospital facilities rival any luxury medical center in the world. Thank you, Manal Healthcare!',
    verified: true,
    featured: true,
    category: 'Cosmetic Surgery',
  },
  {
    id: 'test-004',
    name: 'Emily Chen',
    age: 52,
    country: 'Canada',
    countryFlag: '🇨🇦',
    treatment: 'Breast Cancer Treatment',
    hospital: 'Manal Cancer Care Institute',
    doctor: 'Dr. Vikram Singh',
    rating: 5,
    date: '2025-10-22',
    image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400',
    testimonial: 'Fighting cancer is difficult, but Manal Healthcare made the journey bearable. The oncology team, led by Dr. Singh, provided comprehensive treatment with compassion and expertise. The advanced radiation therapy and personalized care plan helped me beat cancer. I am now cancer-free and eternally grateful.',
    verified: true,
    featured: true,
    category: 'Cancer Treatment',
  },
  {
    id: 'test-005',
    name: 'David Williams',
    age: 38,
    country: 'Australia',
    countryFlag: '🇦🇺',
    treatment: 'Spinal Surgery',
    hospital: 'Manal Neuroscience Institute',
    doctor: 'Dr. Suresh Patel',
    rating: 5,
    date: '2025-10-05',
    image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400',
    testimonial: 'I had chronic back pain for years and was hesitant about spinal surgery. Dr. Patel and his team at Manal Healthcare performed a minimally invasive procedure that changed my life. I can now walk without pain and have returned to my active lifestyle. The technology and expertise here are world-class.',
    verified: true,
    featured: false,
    category: 'Neurology',
  },
  {
    id: 'test-006',
    name: 'Maria Rodriguez',
    age: 35,
    country: 'Germany',
    countryFlag: '🇩🇪',
    treatment: 'IVF Treatment',
    hospital: 'Manal Fertility Center',
    doctor: 'Dr. Kavita Reddy',
    rating: 5,
    date: '2025-09-18',
    image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400',
    testimonial: 'After multiple failed IVF attempts in Germany, we came to Manal Healthcare as our last hope. Dr. Reddy and her team were incredibly supportive throughout the process. We are now proud parents of beautiful twins! The success rate and affordability here are unmatched. Thank you for making our dreams come true.',
    verified: true,
    featured: true,
    category: 'General Surgery',
  },
  {
    id: 'test-007',
    name: 'Ahmed Hassan',
    age: 48,
    country: 'UAE',
    countryFlag: '🇦🇪',
    treatment: 'Liver Transplant',
    hospital: 'Manal Liver Transplant Institute',
    doctor: 'Dr. Ramesh Gupta',
    rating: 5,
    date: '2025-09-01',
    image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400',
    testimonial: 'My liver transplant at Manal Healthcare was performed flawlessly. Dr. Gupta is one of the best transplant surgeons I have encountered. The coordination between the surgical team, ICU staff, and post-transplant care unit was seamless. I am recovering well and living a normal life again.',
    verified: true,
    featured: true,
    category: 'General Surgery',
  },
  {
    id: 'test-008',
    name: 'Linda Brown',
    age: 62,
    country: 'United States',
    countryFlag: '🇺🇸',
    treatment: 'Hip Replacement',
    hospital: 'Manal Orthopedic Center',
    doctor: 'Dr. Arun Kumar',
    rating: 4.5,
    date: '2025-08-14',
    image: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=400',
    testimonial: 'The hip replacement surgery was successful, and I am walking without pain. The hospital was clean, and the staff was helpful. Dr. Kumar is experienced and knowledgeable. My only minor concern was the wait time for some tests, but overall, I am satisfied with the treatment and results.',
    verified: true,
    featured: false,
    category: 'Orthopedic',
  },
  {
    id: 'test-009',
    name: 'Fatima Al-Rashid',
    age: 29,
    country: 'Saudi Arabia',
    countryFlag: '🇸🇦',
    treatment: 'Dental Implants',
    hospital: 'Manal Dental Care Center',
    doctor: 'Dr. Neha Sharma',
    rating: 5,
    date: '2025-08-02',
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400',
    testimonial: 'I received dental implants at Manal Healthcare, and the results are amazing. Dr. Sharma is a perfectionist, and my smile looks natural and beautiful. The dental technology here is advanced, and the hygiene standards are impeccable. I would recommend this to anyone needing dental work.',
    verified: true,
    featured: false,
    category: 'Dental Care',
  },
  {
    id: 'test-010',
    name: 'Peter Anderson',
    age: 55,
    country: 'Canada',
    countryFlag: '🇨🇦',
    treatment: 'Cataract Surgery',
    hospital: 'Manal Eye Care Institute',
    doctor: 'Dr. Rohit Verma',
    rating: 5,
    date: '2025-07-20',
    image: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400',
    testimonial: 'My vision was deteriorating due to cataracts, and I chose Manal Healthcare for the surgery. Dr. Verma performed bilateral cataract surgery, and my vision is now crystal clear. The procedure was painless, and the recovery was quick. The affordability compared to Canada is remarkable.',
    verified: true,
    featured: false,
    category: 'Eye Care',
  },
  {
    id: 'test-011',
    name: 'Grace Okonkwo',
    age: 41,
    country: 'Nigeria',
    countryFlag: '🇳🇬',
    treatment: 'Bariatric Surgery',
    hospital: 'Manal Weight Loss Center',
    doctor: 'Dr. Sandeep Jain',
    rating: 5,
    date: '2025-07-05',
    image: 'https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=400',
    testimonial: 'I struggled with obesity for years, and bariatric surgery at Manal Healthcare changed my life. Dr. Jain and the nutritionist team provided excellent support before and after surgery. I have lost 40 kg and feel healthier and more confident. Thank you for this life-changing experience!',
    verified: true,
    featured: true,
    category: 'General Surgery',
  },
  {
    id: 'test-012',
    name: 'Robert Taylor',
    age: 67,
    country: 'United Kingdom',
    countryFlag: '🇬🇧',
    treatment: 'Prostate Cancer Surgery',
    hospital: 'Manal Cancer Care Institute',
    doctor: 'Dr. Amit Desai',
    rating: 5,
    date: '2025-06-18',
    image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400',
    testimonial: 'Prostate cancer diagnosis was scary, but Manal Healthcare provided hope and healing. Dr. Desai performed robotic-assisted surgery with precision. The pathology reports showed complete cancer removal. The follow-up care and counseling were exceptional. I am now cancer-free and enjoying life with my family.',
    verified: true,
    featured: true,
    category: 'Cancer Treatment',
  },
];

// Utility functions
export function getTestimonialById(id: string): Testimonial | undefined {
  return testimonials.find(t => t.id === id);
}

export function getFeaturedTestimonials(limit: number = 6): Testimonial[] {
  return testimonials
    .filter(t => t.featured)
    .slice(0, limit);
}

export function getTestimonialsByCategory(category: string): Testimonial[] {
  if (category === 'All') return testimonials;
  return testimonials.filter(t => t.category === category);
}

export function getTestimonialStats() {
  const totalTestimonials = testimonials.length;
  const averageRating = testimonials.reduce((sum, t) => sum + t.rating, 0) / totalTestimonials;
  const verifiedCount = testimonials.filter(t => t.verified).length;
  const countries = [...new Set(testimonials.map(t => t.country))].length;

  return {
    total: totalTestimonials,
    averageRating: averageRating.toFixed(1),
    verified: verifiedCount,
    countries,
  };
}
